import pandas as pd

class Source:
    def __init__(s, title: str = "", location: str = "", years: list[int] = [], variables: list[str] = []):
        s.title = title
        s.location = location
        s.years = years
        s.variables = variables
    def as_df(s) -> pd.DataFrame:
        return pd.DataFrame({
            "title": [s.title],
            "location": [s.location],
            "years": [s.years],
            "variables": [s.variables]
            })
    def as_dict(s) -> dict:
        return {
                "title": s.title,
                "location": s.location,
                "years": s.years,
                "variables": s.variables
                }

sources = [Source(
    title = "American Community Survey",
    location = "https://census.gov/", # Update with a more precise link
    years = [],
    variables = []
), Source(
    title = "Current Population Survey",
    location = "https://census.gov/", # Update with a more precise link
    years = [],
    variables = []
), Source(
    title = "Integrated Postsecondary Education Data System (IPEDS) Institution Lookup",
    location = "https://surveys.nces.ed.gov/ipeds/public/survey-materials/index",
    years = [ 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024 ],
    variables = []
), Source(
    title = "National Center for Science and Engineering Statistics",
    location = "https://ncses.nsf.gov/",
    years = [ 2021, 2023 ],
    variables = [
        "Survey of Earned Doctorates",
        "Survey of Graduate Students and Postdoctorates in Science and Engineering",
        "Survey of Doctorate Recipients",
        "Higher Education Research and Development Survey",
        "National Survey of College Graduates"
    ]
), Source(
    title = "Higher Education Research and Development Survey",
    location = "https://ncses.nsf.gov/surveys/higher-education-research-development/2023",
    years = [ 2023 ],
    variables = [
        "Higher education R&D expenditures, ranked by FY 2023 R&D expenditures: FYs 2010–23",
        "Total and federally financed higher education R&D expenditures in mathematics and statistics, ranked by FY 2023 total: FYs 2020–23",
        "Higher education R&D expenditures, by R&D field: FYs 2010–23",
        "Higher education R&D expenditures, by source of funds and R&D field: FY 2023",
        "Higher education R&D expenditures at private institutions, ranked by all R&D expenditures, by source of funds: FY 2023",
        "Higher education R&D expenditures at public institutions, ranked by all R&D expenditures, by source of funds: FY 2023",
        "Higher education R&D expenditures at high-Hispanic-enrollment institutions, ranked by all R&D expenditures, by R&D field: FY 2023",
        "Higher education R&D expenditures at historically black colleges and universities, ranked by all R&D expenditures, by source of funds: FY 2023",
        "Higher education R&D expenditures at high-Hispanic-enrollment institutions, ranked by all R&D expenditures, by source of funds: FY 2023 ",
        "Higher education R&D expenditures at historically black colleges and universities, ranked by all R&D expenditures, by R&D field: FY 2023",
        "Higher education R&D expenditures, by source of funds and R&D field: FY 2023",
        "Higher education R&D expenditures, by R&D field: FYs 2010–23"
    ]
), Source(
    title = "Survey of Earned Doctorates",
    location = "https://ncses.nsf.gov/surveys/earned-doctorates/2023",
    years = [],
    variables = []
), Source(
    title = "Survey of Graduate Students and Postdoctorates in Science and Engineering",
    location = "https://ncses.nsf.gov/surveys/graduate-students-postdoctorates-s-e/2023", # Same as the previous comment
    years = [ 2023 ],
    variables = [
        "Citizenship, ethnicity, and race of graduate students, by detailed field: 2023",
        "Master's and doctoral students within science, engineering, and health fields, by enrollment intensity: 2023",
        "Demographic characteristics of graduate students, postdoctoral appointees, and doctorate-holding nonfaculty researchers in science, engineering, and health: 2023",
        "Graduate students in science, engineering, and health broad fields, by degree program, citizenship, ethnicity, and race: 2023"
    ]
), Source(
    title = "National Survey of College Graduates",
    location = "https://ncses.nsf.gov/pubs/nsf23306/",
    years = [ 2021 ],
    variables = [
        "College graduates, by level of highest degree, minor field of highest degree, and labor force status: 2021",
        "Employed scientists and engineers, by sex, major field of highest degree, ethnicity, race, disability status, and type of disability: 2021",
        "Employed college graduates, by minor occupation and major field of highest degree: 2021",
        "Employed college graduates, by level of highest degree, minor occupation, and primary work activity: 2021",
        "Median annual salaries of full-time employed college graduates, by major occupation, age, level of highest degree, and sex: 2021",
        "Employment counts and median annual salaries of full-time employed scientists and engineers, by major field of highest degree, employment sector, and primary work activity: 2021",
        "College graduates, by broad field of highest degree, father's education, mother's education, level of highest degree, and median amount borrowed to finance undergraduate degree: 2021"
    ]
), Source(
    title = "Bureau of Labor Statistics",
    location = "https://www.bls.gov/",
    years = [],
    variables = []
), Source(
    title = "Occupational Outlook Handbook",
    location = "https://www.bls.gov/ooh/",
    years = [],
    variables = []
), Source(
    title = "Occupational Employment and Wage Statistics",
    location = "https://www.bls.gov/oes/tables.htm",
    years = [],
    variables = []
), Source(
    title = "American Mathematical Society",
    location = "https://ams.org/",
    years = [],
    variables = []
), Source(
    title = "Mathematical Association of America",
    location = "https://maa.org/",
    years = [],
    variables = []
), Source(
    title = "Society for Industrial and Applied Mathematics",
    location = "https://siam.org/",
    years = [],
    variables = []
), Source(
    title = "Association for Women in Mathematics",
    location = "https://awm-math.org/",
    years = [],
    variables = []
), Source(
    title = "Conference Board of the Mathematical Sciences 2021 Survey",
    location = "www.ams.org/learning-careers/data/cbms-survey/",
    years = [2021],
    variables = [
        "Bachelor’s degrees in mathematics, mathematics education, statistics, and computer science in mathematics departments awarded between July 1, 2020 and June 30, 2021, by gender of degree recipient and type of department.",
        "Bachelor’s degrees in statistics departments awarded between July 1, 2020 and June 30, 2021, by gender of degree recipient and type of department.",
        "Enrollment (in thousands) in undergraduate mathematics, statistics, and computer science courses (including distance learning enrollments) in mathematics and statistics departments by level of course and type of department in fall 2021. Numbers in parentheses are (2010, 2015) enrollments.",
        "Number of sections (not including distance learning) of undergraduate mathematics, statistics, and computer science courses in mathematics and statistics departments by level of course and type of department in fall 2021 with fall 2015 figures in parentheses.",
        "Enrollments in distance/remote learning courses (meaning courses offered for credit in which half or more of the instruction occurs with the instructor and the students separated by time and/or place [e.g., courses in which half or more of the course is taught online either synchronously or asynchronously, by computer software, or by other technologies], and other sections for various freshman and sophomore courses, by type of department, in fall 2021. Includes only distance/remote courses offered in normal practice, not courses that became distance/remote due to COVID-19 pandemic. (Fall 2015 data in parentheses.)",
        "Number of sections (excluding distance learning) of calculus-level courses in mathematics departments taught by various types of instructor, by type of department, in fall 2021 with fall 2015 figures in parentheses.",
        "Number of sections (excluding distance learning) of introductory statistics courses taught in mathematics departments and statistics departments by type of instructor and type of department in fall 2021 with fall 2015 figures in parentheses.",
        "Number of sections of advanced mathematics (including operations research) and statistics courses in mathematics departments and of advanced statistics courses in statistics departments taught by tenured/tenure-eligible (TTE) faculty and total number of advanced-level sections by type of department in fall 2021 with fall 2015 data in parentheses.",
        "Number of sections (excluding distance learning) of lower-level computer science courses taught in mathematics departments by type of instructor and type of department in fall 2021 with fall 2015 figures in parentheses.",
        "Number of sections (excluding distance learning) of middle-level computer science courses taught in mathematics departments by type of instructor and type of department in fall 2021 with fall 2015 figures in parentheses.",
        "Average section size (excluding distance learning) for undergraduate mathematics, statistics, and computer science courses in math- ematics and statistics departments by level of course and type of department in fall 2021 with fall 2015 data, when available, in parentheses. Also, all departments’ average section sizes from previous CBMS surveys.",
        "Average recitation size in Mainstream Calculus I and II and other Calculus I courses and in introductory statistics courses that are taught using lecture/recitation method, by type of department in fall 2021, with fall 2015 data in parentheses. Distance learning sections are not included. (A calculus course is “Mainstream” if it leads to the usual upper-division mathematical sciences courses.)",
        "Number of faculty, and of female faculty (F), in various types of mathematics departments and PhD statistics departments by highest degree and type of department in fall 2021. (Fall 2015 figures are in parentheses, and postdocs are included in other full-time (OFT) faculty totals.)",
        "Number of faculty, and of female faculty (F), in mathematics departments combined and of doctoral-level statistics departments in fall 2021. (Fall 2015 figures are in parentheses.)",
        "Number of tenured, tenure-eligible, postdoctoral, and other full-time (OFT) faculty in mathematics departments at four-year colleges and universities by gender and type of department in fall 2021. (Note: Postdoctoral faculty are included in other full-time totals.)",
        "Number of tenured, tenure-eligible, other full-time, and postdoctoral faculty in doctoral-level statistics departments by gender in fall 2021 and 2015. (Postdoctoral faculty are included in other full-time faculty totals.)",
        "Percentage of tenured and tenure-eligible mathematics department faculty and statistics faculty at four-year colleges and universities belonging to various age groups by type of department and gender in fall 2021.",
        "Percentages of full-time faculty belonging to various ethnic groups by gender and type of department in fall 2021. Except for round-off, the percentages within each departmental type sum to 100%.",
        "Percentages of part-time faculty belonging to various ethnic groups by gender and type of department in fall 2021. Except for round-off, the percentages within each departmental type sum to 100%.",
        "Percentage of sections (excluding distance learning sections) in Mainstream Calculus I and Mainstream Calculus II taught by various types of instructors in four-year mathematics departments in fall 2021, by size of sections and type of department. Also average section sizes and enrollments (not including distance learning enrollments).",
        "Percentage of sections (excluding distance learning sections) in Non-Mainstream Calculus I and in Non-Mainstream Calculus II, III, etc. taught by various types of instructors in mathematics departments in fall 2021 by size of sections and type of department. Also average section size and enrollments (not including distance learning enrollments).",
        "Percentage of sections (excluding distance learning sections) in Introductory Statistics courses (for non-majors) taught by various types of instructors in mathematics departments in fall 2021, by size of sections and type of department. Also average section size and enrollments (not including distance learning enrollments).",
        "Percentage of sections (excluding distance learning sections) in Introductory Statistics courses (for non-majors) taught by various types of instructors in statistics departments in fall 2021, by size of sections and type of department. Also average section size and total (non-distance learning) enrollments.",
        "Percentage of mathematics departments using various practices in the teaching of Introductory Statistics (no calculus prerequisite) in fall 2021 by type of department.",
        "Instructional strategies used in Introductory Statistics courses.",
        "Extent of success in the use of technology in Introductory Statistics.",
        "Of departments that offered Introductory Statistics (no calculus prerequisite) in fall 2021 and where a similar course is offered outside the mathematical sciences departments, the average estimated fall 2021 enrollment of all similar courses and an estimate of the total national enrollment.",
        "Total institutional enrollment (in thousands) and percentage of part-time enrollments in two year colleges in fall for 1980 through 2015 and projected enrollments for fall 2021. Enrollments include distance learning but not dual enrollments",
        "Enrollments in mathematics and statistics (no computer science) courses in mathematics programs at two-year colleges in fall 1985, 1990, 1995, 2000, 2005, 2010, 2015, and 2021.",
        "Enrollment in thousands in mathematics and statistics courses (not including dual enrollments; including distance enrollments) in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.",
        "Enrollment in 1000s (not including dual enrollments; including distance enrollments) and percentages of total enrollment in mathematics and statistics courses by type of course in mathematics departments at two-year colleges in fall 2000, 2005, 2010, 2015, and 2021.",
        "Percentage of two-year college mathematics departments teaching mathematics courses in fall 2015 and fall 2021.",
        "Percentage of two-year college mathematics departments teaching selected mathematics courses in the fall terms of 2005, 2010, 2015, and 2021.",
        "Average on-campus section size by type of course in mathematics departments at two-year colleges in fall 2010, 2015, and 2021. Also percentage of sections with enrollment above 30 in fall 2015 and 2021.",
        "Average distance learning section size by type of course in mathematics departments at public two-year colleges in fall 2021. Also percentage of sections with enrollment above 30 in fall 2021.",
        "Average on-campus and distance learning section size for public two-year college mathematics department courses in fall 2021.",
        "Number of sections and number and percentage of sections taught by part-time faculty in mathematics departments at public two-year colleges by type of course in fall 2015 and 2021 (excluding distance learning and dual-enrollment sections).",
        "Percentage of mathematics departments at public two-year colleges which implemented a Pathways course sequence in 2015 and 2021, an Intermediate Algebra prerequisite in 2021, and the types of courses implemented.",
        "Enrollments in distance/remote learning (in 1000s) and percentage of distance/remote learning enrollments (distance learning courses are courses in which half or more of the instruction occurs with the instructor and the students separated by time and/or place facilitated by technology) among all enrollments (excluding dual enrollments) in mathematics departments at two-year colleges in fall 2010, 2015, and 2021.",
        "Percentage of mathematics departments reporting use of distance learning in mathematics departments at two-year colleges in 2013–2021.",
        "Percentage of departments with distance learning that described various factors as significant challenges or somewhat of a challenge in fall 2021.",
        "Percentage of two-year colleges offering various opportunities and services to mathematics students in fall 2010, 2015, and 2021.",
        "Number of full-time permanent faculty, full-time temporary faculty, other full-time faculty, and part-time faculty paid by two-year colleges (TYC) and by a third party (e.g., dual-enrollment instructors) in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.",
        "Teaching assignment for full-time permanent faculty, and teaching and other duties of part-time faculty, in mathematics departments at two-year colleges in fall 2021 (2015 data in parentheses).",
        "Number of full-time permanent faculty in 2020–2021 who were no longer part of the faculty in 2025–2016 and 2021–2022.",
        "Percentage of full-time permanent faculty in mathematics departments at two-year colleges by highest degree in fall 2000, 2005, 2010, 2015, and 2021.",
        "Percentage of full-time permanent faculty in mathematics programs at public two-year colleges by field and highest degree in fall 2021.",
        "Percentage of part-time faculty in mathematics departments at two-year colleges (including those paid by a third party, as in dual-enrollment courses) by highest degree in fall 2000, 2005, 2010, 2015, and 2021.",
        "Percentage of part-time faculty in mathematics departments at two-year colleges (including those paid by a third party, as in dual-enrollment courses) by field and highest degree in fall 2021, with 2015 data in parentheses.",
        "Number and percentage of total full-time permanent faculty in mathematics departments at two-year colleges by gender in fall 2005, 2010, 2015, and 2021.",
        "Percentage of full-time permanent faculty and part-time faculty in mathematics departments at public two-year colleges by gender in fall 2021. Also master’s degrees in mathematics and statistics granted in the U.S. to citizens and resident aliens, by gender, in 2019–20. Part-time faculty paid by a third party are not included.",
        "Percentage and number of ethnic minority full-time permanent faculty in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.",
        "Percentage of full-time permanent faculty in mathematics departments at two-year colleges by ethnicity in fall 2005, 2010, 2015, and 2021",
        "Number and percentage of full-time permanent faculty in mathematics departments at two year colleges by ethnic group, and percentage of women within each ethnic group in fall 2021.",
        "Percentage of full-time permanent faculty and of full-time permanent faculty under age 40 in mathematics departments at public two-year colleges by ethnic group in fall 2021. Also U.S. master’s degrees in mathematics and statistics granted in the U.S. to citizens and resident aliens by ethnic group in 2020–21.",
        "Percentage of ethnic minority part-time faculty in mathematics departments at public two-year colleges in fall 2010, 2015, and 2021.",
        "Number and percentage of part-time faculty in mathematics departments at public two-year colleges by ethnic group, and percentage of women within each ethnic group in fall 2021.",
        "Percentage and number of full-time permanent faculty in mathematics departments at two-year colleges by age in fall 2005, 2010, 2015, and 2021.",
        "Percentage of full-time permanent faculty in mathematics departments at public two-year colleges by age and by gender, and percentage of women by age in fall 2021.",
        "Percentage of newly appointed full-time permanent faculty in mathematics departments at two-year colleges coming from various sources in fall 2015 and 2021.",
        "Percentage of full-time permanent faculty newly appointed in mathematics departments at two-year colleges by highest degree in fall 2015 and 2021.",
        "Percentage of full-time permanent faculty newly appointed in mathematics departments at two year colleges by ethnic group in fall 2015 and 2021. Also percentage of women within each ethnic group in fall 2021.",
        "Percentage of two-year colleges that require periodic teaching evaluations for all full-time or all part-time faculty in fall 2015 and 2021.",
        "Percentage of mathematics departments at public two-year colleges using various methods of evaluating teaching of full- and part-time faculty in fall 2021.",
        "Percentage of two-year colleges that require some form of continuing education or professional development for full-time permanent faculty, and percentage of faculty using various methods to fulfill those requirements, in mathematics departments at two-year colleges in fall 2015 and 2021.",
        "Percentage of program heads classifying various problems as “major” in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.",
        "Percentage of program heads of mathematics departments at public two-year colleges classifying various problems by severity in fall 2021."
    ]
), Source(
    title = "IPUMS",
    location = "https://ipums.org/",
    years = [ 2013 ],
    variables = [
        "Undergraduate loans: total funds borrowed"
        "Year of first bachelor's degree pre-2003 (5-year intervals)",
        "Year of first bachelor degree 2003-onward (5-year intervals)",
        "Field of major for first bachelor degree code",
        "Field of major for first bachelor degree (major group)",
        "Location of school awarding first bachelor's degree (region)",
        "Location of school awarding first bachelor degree (US/non-US)",
        "Education code for first intended major (best code)",
        "Field of intended bachelors degree (major group)",
        "Field of intended bachelors degree (minor group)",
        "First intended major: undecided",
        "Undergraduate grade-point average (GPA)",
        "Financial support for first bachelor degree: Assistantship/work study",
        "Financial support for first bachelor degree: Employer",
        "Financial support for first bachelor degree: Earnings from employment",
        "Financial support for first bachelor degree: Gifts",
        "Financial support for first bachelor degree: Grants",
        "Financial support for first bachelor degree: Loans",
        "Financial support for first bachelor degree: Other",
        "Financial support for first bachelor degree: Loans from relatives",
        "Undergraduate loans: remaining balance",
        "Children indicator: aged 12-17",
        "Children indicator: aged 12-18",
        "Number of children: aged 18 or older",
        "Children indicator: aged 18 or older",
        "Children indicator: age 19 or older",
        "Age",
        "Birth year",
        "Gender",
        "Minority indicator",
        "Race/ethnicity",
        "Place of birth",
        "US citizenship status",
        "Type of US citizen",
        "Type of visa held when first came to US",
        "Total number of children",
        "Number of children: under age 2",
        "Children indicator: under age 2",
        "Number of children: under age 6",
        "Children indicator: under age 6",
        "Number of children: aged 2-5",
        "Children indicator: ages 2-5",
        "Number of children: aged 6-11",
        "Children indicator: ages 6-11",
        "Children indicator: under 12",
        "Number of children: aged 12-17",
        "Career preparation: teaching skills",
        "Career preparation: collaboration/team work skills",
        "Career preparation: writing skills",
        "Year of highest degree since doctorate ",
        "Field of major for highest degree since doctorate ",
        "Field of major for highest degree since doctorate (major group)",
        "Highest degree since doctorate: course costs paid for by employer",
        "Satisfaction with doctoral program",
        "First doctoral degree received between June 1990 and June 1996",
        "Completing doctoral degree affected: level of responsibility",
        "Completing doctoral degree affected: management activities",
        "Completing doctoral degree affected: other",
        "Completing doctoral degree affected: interesting/rewarding work",
        "Completing doctoral degree affected: job security",
        "Completing doctoral degree affected: technically demanding work",
        "Completing doctoral degree affected: salary level",
        "No more training desired",
        "More training: first area",
        "More training: second area",
        "Career preparation: oral communication skills",
        "Career preparation: computer skills",
        "Career preparation: establishing contacts",
        "Career preparation: research integrity/ethics",
        "Career preparation: problem solving skills",
        "Career preparation: subject matter knowledge",
        "Career preparation: management/administrative skills",
        "Career preparation: quantitative skills",
        "Graduate loans: remaining balance",
        "Graduate loans: total funds borrowed",
        "Type of highest certificate or degree",
        "Year of highest degree pre-2003 (5 year intervals)",
        "Year of highest degree 2003-onward (5 year intervals)",
        "Field of major for highest degree ",
        "Field of major for highest degree (major group)",
        "Location of school awarding highest degree",
        "School awarding highest degree located in the US",
        "Financial support for highest degree: assistantship/work study",
        "Financial support for highest degree: financial assistance from employer",
        "Financial support for highest degree: earnings from employment",
        "Financial support for highest degree: gifts",
        "Financial support for highest degree: grants",
        "Financial support for highest degree: loans",
        "Financial support for highest degree: other",
        "Financial support for highest degree: loans from parents",
        "Likelihood of choosing same field of study for highest degree",
        "Type of degree",
        "Year of most recent degree (5-year intervals",
        "Year of most recent degree (5-year intervals",
        "Field of major for most recent degree",
        "Field of study of major for most recent degree (major group)",
        "Location of school awarding most recent degree",
        "School awarding most recent degree located in the US",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Job market for other than postdocs",
        "Job market for postdocs",
        "Individual identification number[preselected]",
        "Reference ID number (original)",
        "Survey year[preselected]",
        "SESTAT weight[preselected]",
        "Sample identifier[preselected]",
        "Survey identifier[preselected]",
        "Survey cohort",
        "Survey mode",
        "Sequence number",
        "Two-year associates degree ",
        "Not held career path job since receiving doctorate ",
        "Most important resource for career search ",
        "Second most important resource for career search ",
        "Job seeking resources used: initiated direct contacts ",
        "Job seeking resources used: electronic postings ",
        "Job seeking resources used: faculty/advisors ",
        "Job seeking resources used: colleagues/friends ",
        "Job seeking resources used: newspapers ",
        "Job seeking resources used: other ",
        "Job seeking resources used: professional journals ",
        "Job seeking resources used: professional meetings ",
        "Job seeking resources used: college placement office ",
        "Job seeking resources used: professional recruiters ",
        "Search for job limited by: debt ",
        "Search for job limited by: family responsibilities ",
        "Search for job limited by: desire to not relocate ",
        "Search for job limited by: suitable job not available ",
        "Search for job limited by: other ",
        "Search for job limited by: spouse's career ",
        "Reasons for not working: family responsibilities ",
        "Reasons for not working: illness/disability ",
        "Reasons for not working: layoff ",
        "Reasons for not working: did not need/want to work ",
        "Reasons for not working: suitable job not available ",
        "Reasons for not working: other ",
        "Reasons for not working: illness, retired or other (combined) ",
        "Reasons for not working: retired ",
        "Reasons for not working: student ",
        "Career-path job ",
        "Seeking career-path job ",
        "Time started career-path job ",
        "Sought career path job ",
        "Sought or held career path job ",
        "Held or accepted career path job ",
        "When began working on job ",
        "How doctoral degree would help career ",
        "Still holding career path job ",
        "Relationship of career path job to doctoral degree field ",
        "Work wanted after completing doctorate: management/administration ",
        "Work wanted after completing doctorate: professional practice ",
        "Work wanted after completing doctorate: research ",
        "Work wanted after completing doctorate: teaching ",
        "Work wanted after completing doctorate: other ",
        "Desired employment setting at beginning of doctorate ",
        "New job offered what level of: responsibility ",
        "New job offered what level of: salary ",
        "New job offered what level of: knowledge/skill utilization ",
        "Time elapsed between receiving doctorate and accepting career path job ",
        "Attended community college ",
        "Reasons attend community college: high school advanced placement program ",
        "Reasons attend community college: complete associates degree ",
        "Reasons attend community college: complete credit towards bachelors degree ",
        "Reasons attend community college: change academic/occupational field ",
        "Reasons attend community college: prepare for college ",
        "Reasons attend community college: financial reasons ",
        "Reasons attend community college: complete high school equivalency ",
        "Reasons attend community college: leisure ",
        "Reasons attend community college: other ",
        "Reasons attend community college: increase opportunities for promotion ",
        "Reasons attend community college: acquire further skills in field ",
        "Reasons for not taking courses: needed break ",
        "Reasons for not taking courses: no longer certain of field ",
        "Reasons for not taking courses: family ",
        "Reasons for not taking courses: financial reasons ",
        "Reasons for not taking courses: achieved educational goals ",
        "Reasons for not taking courses: job ",
        "Reasons for not taking courses: moved ",
        "Reasons for not taking courses: waiting for next school term ",
        "Reasons for not taking courses: other ",
        "Reasons for not taking courses: most important reason ",
        "Reasons for not taking courses: second most important reason ",
        "School-related costs paid by employer ",
        "Sources of financial support for courses since college: assistantships/work study ",
        "Sources of financial support for courses since college: employer ",
        "Sources of financial support for courses since college: earnings from employment ",
        "Sources of financial support for courses since college: gifts parents/relatives ",
        "Sources of financial support for courses since college: grants/scholarships/etc. ",
        "Sources of financial support for courses since college: loans from institution ",
        "Sources of financial support for courses since college: other ",
        "Sources of financial support for courses since college: loans from parents/relatives ",
        "Likelihood of taking additional college courses ",
        "Full-time/part-time student status ",
        "Taking courses during reference week ",
        "Type of degree working on during reference week ",
        "Took college courses after completing most recent degree ",
        "Type of degree working on since after college ",
        "Type of degree working on since most recent degree ",
        "Completed a degree since the last survey ",
        "Enrolled in other than courses after completing most recent degree ",
        "Took courses or enrolled in other way after completing most recent degree ",
        "Region, college/university attended during reference week (US/non-US) ",
        "Field of major for field of study after most recent degree ",
        "Field of study after earning degree ",
        "Field of major for current degree (detailed code) ",
        "Field of major for current degree (minor code) ",
        "Field of major for current degree (major code) ",
        "Field of major for degree working on during the week of February 1st ",
        "No primary field of study in courses after college ",
        "Reasons for taking courses: increase advancement opportunities ",
        "Reasons for taking courses: further education before career ",
        "Reasons for taking courses: facilitate academic/occupational field change ",
        "Reason for taking courses during reference week: expected/required by employer ",
        "Reason for taking courses during reference week: prepare for graduate school ",
        "Reason for taking courses during reference week: leisure/personal interest ",
        "Reason for taking courses during reference week: licensure/certification ",
        "Reason for taking courses during reference week: other ",
        "Reason for taking courses during reference week: grad school, required by employer, other ",
        "Reason for taking courses during reference week: gain further skills in field ",
        "Reasons for taking courses: expected/required by employer ",
        "Reasons for taking courses: prepare for graduate school ",
        "Employer sector ",
        "Employer sector (detailed code) ",
        "Size of employer ",
        "Employer: main business ",
        "Principal employer came into being as a new business within last 5 years ",
        "Employer located in the US ",
        "US region code for employer ",
        "Federal government support indicator ",
        "Federal agency supporting work: Agriculture ",
        "Federal agency supporting work: AID ",
        "Federal agency supporting work: Commerce ",
        "Federal agency supporting work: Education ",
        "Federal agency supporting work: Agency unknown ",
        "Federal agency supporting work: Defense ",
        "Federal agency supporting work: Energy ",
        "Federal agency supporting work: Transportation ",
        "Federal agency supporting work: EPA ",
        "Federal agency supporting work: HHS ",
        "Federal agency supporting work: HUD ",
        "Federal agency supporting work: Interior ",
        "Federal agency supporting work: Justice ",
        "Federal agency supporting work: Labor ",
        "Federal agency supporting work: NASA ",
        "Federal agency supporting work: NIH ",
        "Federal agency supporting work: NRC ",
        "Federal agency supporting work: NSF ",
        "Federal agency supporting work: Other ",
        "Federal agency supporting work: State ",
        "Federal agency supporting work: VA ",
        "Reason job unrelated to doctoral degree: career change ",
        "Reason job unrelated to doctoral degree: working conditions ",
        "Reason job unrelated to doctoral degree: family-related reasons ",
        "Reason job unrelated to doctoral degree: job location ",
        "Reason job unrelated to doctoral degree: job in doctoral field not available ",
        "Reason job unrelated to doctoral degree: other ",
        "Reason job unrelated to doctoral degree: pay/promotion opportunities ",
        "Concerned about someone else in household losing job ",
        "No other working adult in household ",
        "Reasons for losing/leaving job: other ",
        "Reasons for losing/leaving job: work reorganized/restructured ",
        "Reasons for losing/leaving job: company had insufficient revenue ",
        "Reasons for losing/leaving job: self-operated business ended ",
        "Reasons for losing/leaving job: company taken over ",
        "Lost or left job due to employer closing or downsizing ",
        "Year last worked ",
        "Previously retired ",
        "Reasons for working part-time: retired ",
        "Working part-time but wanted to work full-time ",
        "Reasons for working part-time: family ",
        "Reasons for working part-time: illness/disability ",
        "Reasons for working part-time: not need/want work ",
        "Reasons for working part-time: suitable full-time job not available ",
        "Reasons for working part-time: other ",
        "Reasons for working part-time: student ",
        "Labor force status ",
        "Working for pay during reference week ",
        "Full-time/part-time status ",
        "Working both current and previous reference weeks ",
        "Employment status, current and previous reference weeks ",
        "Full-time, years of professional work experience ",
        "Part-time, years of professional work experience ",
        "Principal job hours worked ",
        "Principal job: hours per week typically worked (group) ",
        "Principal job salary: weeks per year basis ",
        "Principal job weeks salary based on year (group) ",
        "Available benefits: health insurance ",
        "Available benefits: pension/retirement plan ",
        "Available benefits: profit-sharing plan ",
        "Available benefits: paid vacation/sick/personal days ",
        "Not working, looking for work ",
        "Have not found new job ",
        "Months to find new job ",
        "Preferred type of working arrangement ",
        "Concerned about losing job ",
        "Year, left/lost job ",
        "Reasons for losing/leaving job: company closed down ",
        "Reasons for losing/leaving job: company moved ",
        "Year received high school diploma (group) ",
        "Place attended high school (recode) ",
        "No high school diploma (did not finish high school) ",
        "Salary (annualized) ",
        "Total earned income before deductions in previous year (public use) ",
        "Total household income: 1996 ",
        "CPI conversion factor - current year ",
        "CPI conversion factor - previous year ",
        "International collaboration activity: travel abroad for collaboration ",
        "International collaboration activity: foreign collaborators travel to US ",
        "International collaboration activity: use web-based/virtual technology ",
        "Work benefits from: long distance communication ",
        "Work benefits from: long-term visits ",
        "Work benefits from: short-term visits ",
        "Conducted research outside US ",
        "Length of last trip conducting research outside US ",
        "Would consider conducting research outside US ",
        "Increasing interest in research outside US: family-related reasons ",
        "Increasing interest in research outside US: better financial support ",
        "Increasing interest in research outside US: better foreign language training ",
        "Increasing interest in research outside US: better access to research opportunities ",
        "Increasing interest in research outside US: other ",
        "Increasing interest in research outside US: better sabbatical leave policy ",
        "Reason not conducted research outside US: family-related reasons ",
        "Reason not conducted research outside US: no funding ",
        "Reason not conducted research outside US: no host ",
        "Reason not conducted research outside US: no interest ",
        "Reason not conducted research outside US: concerned about losing place ",
        "Reason not conducted research outside US: lack of foreign language skills ",
        "Reason not conducted research outside US: not relevant to my career ",
        "Reason not conducted research outside US: other ",
        "Reason not conducted research outside US: no time ",
        "International collaboration indicator ",
        "International collaboration activity: communicate by phone/email ",
        "Relationship with principal employer: short term ",
        "Relationship with principal employer: self-employed ",
        "Relationship with principal employer: job sharing ",
        "Relationship with principal employer: temp/employment agency ",
        "Area or tech used during typical week: advanced materials ",
        "Area or tech used during typical week: biotech ",
        "Area or tech used during typical week: high performance computing ",
        "Area or tech used during typical week: semiconductor devices ",
        "Area or tech used during typical week: flexible manufacturing, robotics ",
        "Area or tech used during typical week: software producibility ",
        "Area or tech used during typical week: sensor and signal processing ",
        "Energy-related activity most involved in work ",
        "Energy source involved most ",
        "Most important reason for working outside field of highest degree ",
        "Second most important reason for working outside field of highest degree ",
        "Reason for working outside field of highest degree: career change ",
        "Reason for working outside field of highest degree: working conditions ",
        "Reason for working outside field of highest degree: family-related reasons ",
        "Reason for working outside field of highest degree: job location ",
        "Reason for working outside field of highest degree: suitable job not available ",
        "Reason for working outside field of highest degree: Other ",
        "Reason for working outside field of highest degree: pay/promotion ",
        "Faculty rank and tenure status ",
        "Academic position: adjunct faculty ",
        "Academic position: dean or president ",
        "Academic position: not applicable ",
        "Academic position: research assistant, teaching assistant or other ",
        "Academic position: postdoc ",
        "Academic position: research faculty ",
        "Academic position: teaching faculty ",
        "Alternative work arrangement ",
        "Main reason for alternative work arrangement ",
        "Second most important reason for alternative work arrangement ",
        "Reason for alternative work arrangement: own boss ",
        "Reason for alternative work arrangement: gain experience ",
        "Reason for alternative work arrangement: family-related reasons ",
        "Reason for alternative work arrangement: schedule flexibility ",
        "Reason for alternative work arrangement: other ",
        "Reason for alternative work arrangement: better pay ",
        "Reason for alternative work arrangement: status changed to temporary ",
        "Reason for alternative work arrangement: school or training program ",
        "Reason for alternative work arrangement: only type of work I could find ",
        "Relationship with principal employer: work from home ",
        "Relationship with principal employer: work contracted out by employer ",
        "Relationship with principal employer: other ",
        "Job satisfaction ",
        "Satisfaction principal job's opportunities for advancement ",
        "Satisfaction principal job benefits ",
        "Satisfaction principal job's intellectual challenge ",
        "Satisfaction principal job's degree of independence ",
        "Satisfaction principal job's job location ",
        "Satisfaction principal job's level of responsibility ",
        "Satisfaction principal job salary ",
        "Satisfaction principal job's job security ",
        "Satisfaction principal job's contribution to society ",
        "Principal job related to highest degree ",
        "Job code for principal job ",
        "Job code for principal job (major group) ",
        "Job code for principal job (detailed code) ",
        "Relationship of second job to highest degree ",
        "Second job during reference week ",
        "Job code for second job ",
        "Job code for second job (major group) ",
        "Respondent location ",
        "Reasons for coming to U.S.: most important reason ",
        "Reasons for coming to U.S.: second most important reason ",
        "Factors important to come to U.S.: educational opportunities ",
        "Factors important to come to U.S.: family-related reasons ",
        "Factors important to come to U.S.: scientific/professional infrastructure ",
        "Factors important to come to U.S.: job/economic opportunities ",
        "Factors important to come to U.S.: other ",
        "Respondent location ",
        "Reasons for coming to U.S.: most important reason ",
        "Reasons for coming to U.S.: second most important reason ",
        "Factors important to come to U.S.: educational opportunities ",
        "Factors important to come to U.S.: family-related reasons ",
        "Factors important to come to U.S.: scientific/professional infrastructure ",
        "Factors important to come to U.S.: job/economic opportunities ",
        "Factors important to come to U.S.: other ",
        "Work activities on principal job: professional services ",
        "Work activities on principal job: teaching ",
        "Work activities on principal job: accounting, finance, contracts ",
        "Work activities on principal job : applied research ",
        "Work activities on principal job: basic research ",
        "Work activities on principal job: computer applications ",
        "Work on principal job: work with others in same organization ",
        "Work on principal job: work with immediate group or team ",
        "Work on principal job: work with others in other US organization ",
        "Supervisory work ",
        "Number of papers (co)authored presented ",
        "Number of papers presented (intervaled) ",
        "Named as inventor for U.S patent ",
        "Number of articles authored (intervals) ",
        "Number of articles authored ",
        "Number of professional society memberships ",
        "Attended professional meetings in past year ",
        "Books or monographs (co)authored accepted for publication indicator ",
        "Work similar to what you expected to be doing ",
        "Most hours, work activity ",
        "Summarized primary work activity ",
        "Second most hours, work activity ",
        "Summarized secondary work activity ",
        "Area devoted most hours ",
        "Activity, computer applications ",
        "Activity, development and design ",
        "Activity, management/sales ",
        "Activity, research and development ",
        "Activity, research, development, and teaching ",
        "Activity, research (basic and/or applied) ",
        "Activity, teaching ",
        "Work activities on principal job: development ",
        "Work activities on principal job: design ",
        "Work activities on principal job: employee relations ",
        "Work activities on principal job: management and administration ",
        "Work activities on principal job: other ",
        "Work activities on principal job: production, operations, maintenance ",
        "Work activities on principal job: quality or productivity management ",
        "Work activities on principal job: sales, purchasing, marketing ",
        "Job code for last job (major group) ",
        "Job code for last job (public use) ",
        "Reason for changing employer or job: change in career/professional interests ",
        "Reason for changing employer or job: working conditions ",
        "Reason for changing employer or job: family-related reasons ",
        "Reason for changing employer or job: laid off/job terminated ",
        "Reason for changing employer or job: job location ",
        "Reason for changing employer or job: other ",
        "Reason for changing employer or job: pay, promotion ",
        "Reason for changing employer or job: retired ",
        "Reason for changing employer or job: school-related reasons ",
        "Offered buy-out ",
        "Job code for principal job in 1988 (major group) ",
        "Job code for principal job in 1988 ",
        "Technical expertise required by spouse/partner job: sciences ",
        "Technical expertise required by spouse/partner job: other ",
        "Technical expertise required by spouse/partner Job: social sciences ",
        "Attended work-related training ",
        "Most important reason for taking work-related training ",
        "Reason for attending training: increase advancement opportunities ",
        "Reason for attending training: facilitate occupation change ",
        "Reason for attending training: facilitate occupation change to different field ",
        "Reason for attending training: required/expected by employer ",
        "Reason for attending training: licensure/certification ",
        "Reason for attending training: learn skills for recently acquired position ",
        "Reason for attending training: increase advancement opportunities in current occupation ",
        "Reason for attending training: other ",
        "Reason for attending training: leisure/personal interest ",
        "Reason for attending training: acquire further skills/knowledge ",
        "Area of work-related training: general professional training ",
        "Area of work-related training: management training ",
        "Area of work-related training: other ",
        "Area of work-related training: technical training ",
        "Licensed/certified in occupation ",
        "Job required technical expertise: natural sciences ",
        "Job required technical expertise: other ",
        "Job required technical expertise: social sciences ",
    ]
), Source(
    title = "Data.gov",
    location = "https://data.gov/",
    years = [],
    variables = []
), Source(
    title = "Harvard Dataverse",
    location = "https://dataverse.harvard.edu/",
    years = [],
    variables = []
), Source(
    title = "Pewresearch",
    location = "https://pewresearch.org/",
    years = [],
    variables = []
), Source(
    title = "Urban Institute",
    location = "https://urban.org/",
    years = [],
    variables = []
)]

ts = []
ls = []
ys = []
vs = []

for source in sources:
    ts.append(source.title)
    ls.append(source.location)
    ys.append(source.years)
    vs.append(source.variables)

df = pd.DataFrame({
    "title": ts,
    "location": ls,
    "years": ys,
    "variables": vs
})

df.to_csv("data/variables.csv")
df.to_hdf("data/collected_data.h5", key = "variables")
