import pandas as pd

class Source:
    def __init__(s, title: str = "", location: str = "", years: list[int] = [], variables: list[str] = [], multiple_choices: list[str] = [], multiple_selects: list[str] = [], table_inputs: list[str] = [], written_responses: list[str] = []):
        s.title = title
        s.location = location
        s.years = years
        s.variables = variables
        s.multiple_choices = multiple_choices
        s.multiple_selects = multiple_selects
        s.table_inputs = table_inputs
        s.written_responses = written_responses
    def as_df(s) -> pd.DataFrame:
        return pd.DataFrame({
            "title": [s.title],
            "location": [s.location],
            "years": [s.years],
            "variables": [s.variables]
            })
    def as_dict(s) -> dict:
        return {
                "title": s.title,
                "location": s.location,
                "years": s.years,
                "variables": s.variables
                }

sources = [Source(
    title = "American Community Survey",
    location = "https://census.gov/", # Update with a more precise link
    years = [],
    variables = []
), Source(
    title = "Current Population Survey",
    location = "https://census.gov/", # Update with a more precise link
    years = [],
    variables = []
), Source(
    title = "Integrated Postsecondary Education Data System (IPEDS) Institution Lookup",
    location = "https://surveys.nces.ed.gov/ipeds/public/survey-materials/index",
    years = [ 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024 ],
    variables = [],
    written_responses = ['Your institution reported to the GR survey component as having the following number of students who did not complete, but were still enrolled at your institution:\n', 'How many staff from your institution only were involved in the data collection and reporting process of this survey component?\nNumber of Staff (including yourself)\n', 'How many hours did you and others from your institution only spend on each of the steps below when responding to this survey component? Exclude the hours spent collecting data for state and other reporting purposes.\nRevising Data to Match\nStaff member Collecting Data Needed Entering Data Revising and Locking Data\nIPEDS Requirements\nYour office hours hours hours hours\nOther offices hours hours hours hours\n', 'You may use the box below to provide additional context for the data you have reported above. Context notes will be posted on the College Navigator website.\nTherefore, you should write all context notes using proper grammar (e.g., complete sentences with punctuation) and common language that can be easily understood by students and parents (e.g., spell out acronyms).\n', 'Graduation Rates for 100%, 150%, and 200% of\nnormal time – Cohort Year 2020\nGraduation Rate – 100% of normal time (%)\nGraduation Rate – 150% of normal time (%)\nGraduation Rate – 200% of normal time (%)\n', "You may use the space below to provide context for the data you've reported above.\n", 'How many staff from your institution only were involved in the data collection and reporting process of this survey component?\nNumber of Staff (including yourself)\n', "You may use the space below to provide context for the data you've reported above.\n", 'How many staff from your institution only were involved in the data collection and reporting process of this survey component?\nNumber of Staff (including yourself)\n', 'You may use the box below to provide additional context for the data you have reported above. Context notes will be posted on the College Navigator website.\nTherefore, you should write all context notes using proper grammar (e.g., complete sentences with punctuation) and common language that can be easily understood by students and parents (e.g., spell out acronyms).\n'],
    multiple_choices = ['Do you have students to report who, 1) received an award between 151% and 200% of the normal time to complete OR are still enrolled as of 200% of normal time?\nNo\nYes\n', 'Is the library collection entirely electronic?\nNo Yes\n', 'Does your institution have Library Staff?\nNo Yes\n', 'Does your institution have Interlibrary Loan Services ?\nNo Yes\n', 'Were your annual total library expenses (including staff salaries and wages) for Fiscal Year 2024:\nLess than $100,000 Greater than or equal to $100,000\n', 'Is the library collection entirely electronic?\nNo Yes\n', 'Does your institution have Library Staff?\nNo Yes\n', 'Does your institution have Interlibrary Loan Services ?\nNo Yes\n', 'Were your annual total library expenses (including staff salaries and wages) for Fiscal Year 2024:\nLess than $100,000 Greater than or equal to $100,000\n', '4. Do you offer food or meal plans to your students?\nIf you answer Yes to this question, you will be expected to report a food charge or combined food and housing charge (C10).\nNo\nYes - Enter the number of meals per week for the meal plan with the largest number of meals available\nYes - Number of meals per week can vary (e.g., students charge meals against a meal card)\n', '10. For the purpose of awarding institutional financial aid, does your institution require additional financial information separate from the FAFSA form?\nNo\nYes (please include a website link to where your institution’s website explains what additional financial information is required.)\nLink URL: http://\n', '2. Are all full-time, first-time degree/certificate-seeking students required to live on campus or in institutionally controlled housing? This is only a screening question, and your response does not show up on College Navigator.\nIf you answer Yes to this question, you will not be asked to report off-campus food and housing in the cost of attendance. If you make ANY exceptions to this rule, please answer No so that this does not cause conflicts with the average net price calculation. Misreporting may lead to an inaccurate average net price calculation for your institution.\nNo\nYes, and we do not make ANY (even one) exceptions to this rule\n', '7. Indicate whether or not your institution participates in a Promise program.\nNo\nYes\n', '1. Does your institution offer institutionally-controlled housing (on-campus and/or off-campus)? If you answer Yes to this question, you will be expected to specify a housing capacity, and to report a housing charge or a combined food and housing charge.\nNo\nYes\nSpecify housing capacity for academic year 2024-25\n'],
    multiple_selects = ['You may use the box below to provide additional context for the data you have reported above. Context notes will be posted on the College Navigator website.\nTherefore, you should write all context notes using proper grammar (e.g., complete sentences with punctuation) and common language that can be easily understood by students and parents (e.g., spell out acronyms).\nNon-applicable\nThe Cost of Attendance varies by program.\nThe Cost of Attendance or tuition and fee methodology changed from last year.\nWe allow special Cost of Attendance allowance additions for some programs and student categories.\nCost of Attendance updates are based on a recent (prior or current year) cost survey.\nTuition and fees, and Cost of Attendance components vary by campus location.\nThis is a U.S. Service Academy. All costs are covered, and students receive a stipend in exchange for a U.S. Armed Forces service commitment.\nFirst-year students must live on campus.\nThe Tuition and Fees includes the estimated cost of a computer required for all students.\nThe Tuition and Fees includes the cost of books and supplies.\nThe Books and Supplies includes the estimated cost of a computer required for all students.\nThe Cost of Attendance (COA) is based on a weighted average of student living arrangement categories while enrolled.\nThe Cost of Attendance (COA) is based on a weighted average of costs for all students across Title IV eligible programs.\nOther\n', '8. Indicate whether or not any of the following alternative tuition plans are offered by your institution.\nNo\nYes [Check all that apply]\nTuition guarantee\nPrepaid tuition plan\nTuition payment plan\nOther (specify in box below)\n', "6. For institutions that charge an application fee, can the application fee be waived for applicants that demonstrate financial need?\nNo\nYes (please indicate for which level(s) application fee can be waived)\nUndergraduate programs\nGraduate programs (not including Doctor's-Professional practice)\nDoctor’s-Professional Practice programs\n", '3. Does your institution charge different tuition rates for in-district, in-state, or out-of-state students? If you answer Yes to this question, you will be expected to report different tuition amounts for in-district, in-state, and out-of-state students (as applicable).\nOnly select YES if you charge different tuition by students’ residence status. You should not select YES and then report the same tuition rate 3 times.\nNo\nYes, please check all tuition rates charged by your institution\nIn-district\nIn-state\nOut-of-state\n', "5. Does your institution charge an application fee?\nNo\nYes - select checkboxes for the student level(s) that have an application fee and report the amount of application fee(s) in Section 1 Part A.\nGraduate programs (not including Doctor's-Professional practice)\nDoctor’s-Professional Practice programs\n"],
    table_inputs = ['This survey component was prepared by:\nKeyholder SFA Contact HR Contact\nFinance Contact Academic Library Contact Other\nName:\nEmail:\n', 'Graduation rates\n1 Revised cohort\n2 Exclusions within 150%\n3 Adjusted cohort 150%\n4 Number of students in the cohort who completed a program within 100% of normal time to completion\n5 Number of students in the cohort who completed a program within 150% of normal time to completion\n6 Additional exclusions (between 151% and 200% of normal time)\n7 Adjusted cohort 200% (line 3 - line 6)\nNumber of students in the cohort who completed a program between 151% and 200% of normal time to\n8\ncompletion\n9 Still enrolled as of 200% of normal time to completion\n10 Total completers within 200% of normal time (line 5 + line 8)\n', 'Expenses Amount\nBranch and independent libraries\nSalaries and wages\nFringe benefits\nTotal materials/services expenses\nTotal operations and maintenance expenses\nTotal Expenses\n', 'Operations and maintenance expenses\nPreservation services\nAll other operations and maintenance expenses\nTotal operations and maintenance expenses\n', 'This survey component was prepared by:\nKeyholder SFA Contact HR Contact\nFinance Contact Academic Library Contact Other\nName:\nEmail:\n', 'Expenses Amount\nTotal salaries and wages for the library staff\n', 'How many hours did you and others from your institution only spend on each of the steps below when responding to this survey component? Exclude the hours spent collecting data for state and other reporting purposes.\nRevising Data to Match\nStaff member Collecting Data Needed Entering Data Revising and Locking Data\nIPEDS Requirements\nYour office hours hours hours hours\nOther offices hours hours hours hours\n', 'Interlibrary Loan Services Number Prior Year Amount\nTotal interlibrary loans and documents provided to other libraries\nTotal interlibrary loans and documents received\n', 'Materials/services expenses\nOne-time purchases of books, serial back-files, and other materials\nOngoing commitments to subscriptions\nAll other materials/services costs\nTotal materials/services expenses\n', 'You may use the box below to provide additional context for the data you have reported above.\n', 'Library Staff Number of FTEs Prior Year Amount\nLibrarians\nOther Professional Staff\nAll Other Paid Staff (Except Student Assistants)\nStudent Assistants\nTotal\n', 'Are staff fringe benefits paid out of the library budget?\nNo\nYes Total Fringe benefits\n', 'Total Expenses\nTotal Expenses (minus Fringe Benefits)\n', 'Prior Year Amount\nIndicate the number of branch and independent libraries\n(exclude the main or central library).\n', 'Physical Digital/Electronic Total\nLibrary Collections\nPrior Year Prior Year\nAmount Amount\nBooks\nDatabases\nMedia\nSerials\nTotal\nLibrary Circulation\n', 'Library Collections/Circulation Physical Digital/Electronic\nBooks\nDatabases\nMedia\nSerials\nTotal\nLibrary Circulation\nInterlibrary Loan Services\nLibrary Staff\n', 'Expenses Amount\nBranch and independent libraries\nSalaries and wages\nFringe benefits\nTotal materials/services expenses\nTotal operations and maintenance expenses\nTotal Expenses\n', 'Operations and maintenance expenses\nPreservation services\nAll other operations and maintenance expenses\nTotal operations and maintenance expenses\n', 'This survey component was prepared by:\nKeyholder SFA Contact HR Contact\nFinance Contact Academic Library Contact Other\nName:\nEmail:\n', 'Expenses Amount\nTotal salaries and wages for the library staff\n', 'How many hours did you and others from your institution only spend on each of the steps below when responding to this survey component? Exclude the hours spent collecting data for state and other reporting purposes.\nRevising Data to Match\nStaff member Collecting Data Needed Entering Data Revising and Locking Data\nIPEDS Requirements\nYour office hours hours hours hours\nOther offices hours hours hours hours\n', 'Interlibrary Loan Services Number Prior Year Amount\nTotal interlibrary loans and documents provided to other libraries\nTotal interlibrary loans and documents received\n', 'Materials/services expenses\nOne-time purchases of books, serial back-files, and other materials\nOngoing commitments to subscriptions\nAll other materials/services costs\nTotal materials/services expenses\n', 'You may use the box below to provide additional context for the data you have reported above.\n', 'Library Staff Number of FTEs Prior Year Amount\nLibrarians\nOther Professional Staff\nAll Other Paid Staff (Except Student Assistants)\nStudent Assistants\nTotal\n', 'Are staff fringe benefits paid out of the library budget?\nNo\nYes Total Fringe benefits\n', 'Total Expenses\nTotal Expenses (minus Fringe Benefits)\n', 'Prior Year Amount\nIndicate the number of branch and independent libraries\n(exclude the main or central library).\n', 'Physical Digital/Electronic Total\nLibrary Collections\nPrior Year Prior Year\nAmount Amount\nBooks\nDatabases\nMedia\nSerials\nTotal\nLibrary Circulation\n', 'Library Collections/Circulation Physical Digital/Electronic\nBooks\nDatabases\nMedia\nSerials\nTotal\nLibrary Circulation\nInterlibrary Loan Services\nLibrary Staff\n', 'Undergraduate students (all) In-district Prior year In-state Prior year Out-of-state Prior year\nFull-time\nTuition\nRequired fees\nPart-time\nTuition (per credit hour charges)\nRequired fees\n', 'Charges for full academic year 2021‑22 2022‑23 2023‑24 2024‑25\nTuition Guarantee\nTuition and required fees: (check only if applicable Guaranteed\nto entering students increase %\nin 2024-25)\nIn-district\nTuition\nRequired fees\nTuition + fees total\nIn-state\nTuition\nRequired fees\nTuition + fees total\nOut-of-state\nTuition\nRequired fees\nTuition + fees total\nBooks and supplies\nOn-campus:\nFood and housing\nOther expenses\nFood and housing and other expenses total\nOff-campus (not with family):\nFood and housing\nOther expenses\nFood and housing and other expenses total\nOff-campus (with family):\nFood and housing\nOther expenses\nFood and housing and other expenses total\n', "If the institution charges an application fee, indicate the amount.\nAmount Prior year\nUndergraduate application fee\nGraduate application fee (not including Doctor's-Professional practice)\nDoctor’s-Professional Practice programs\n", 'Graduate students (not including Doctor’s-Professional practice) In-district Prior year In-state Prior year Out-of-state Prior year\nFull-time\nTuition\nRequired fees\nPart-time\nTuition (per credit hour charges)\nRequired fees\n']


), Source(
    title = "National Center for Science and Engineering Statistics",
    location = "https://ncses.nsf.gov/",
    years = [ 2021, 2023 ],
    variables = [
        "Survey of Earned Doctorates",
        "Survey of Graduate Students and Postdoctorates in Science and Engineering",
        "Survey of Doctorate Recipients",
        "Higher Education Research and Development Survey",
        "National Survey of College Graduates"
    ]
), Source(
    title = "Higher Education Research and Development Survey",
    location = "https://ncses.nsf.gov/surveys/higher-education-research-development/2023",
    years = [ 2023 ],
    variables = [
        "Higher education R&D expenditures, ranked by FY 2023 R&D expenditures: FYs 2010–23",
        "Total and federally financed higher education R&D expenditures in mathematics and statistics, ranked by FY 2023 total: FYs 2020–23",
        "Higher education R&D expenditures, by R&D field: FYs 2010–23",
        "Higher education R&D expenditures, by source of funds and R&D field: FY 2023",
        "Higher education R&D expenditures at private institutions, ranked by all R&D expenditures, by source of funds: FY 2023",
        "Higher education R&D expenditures at public institutions, ranked by all R&D expenditures, by source of funds: FY 2023",
        "Higher education R&D expenditures at high-Hispanic-enrollment institutions, ranked by all R&D expenditures, by R&D field: FY 2023",
        "Higher education R&D expenditures at historically black colleges and universities, ranked by all R&D expenditures, by source of funds: FY 2023",
        "Higher education R&D expenditures at high-Hispanic-enrollment institutions, ranked by all R&D expenditures, by source of funds: FY 2023 ",
        "Higher education R&D expenditures at historically black colleges and universities, ranked by all R&D expenditures, by R&D field: FY 2023",
        "Higher education R&D expenditures, by source of funds and R&D field: FY 2023",
        "Higher education R&D expenditures, by R&D field: FYs 2010–23"
    ]
), Source(
    title = "Survey of Earned Doctorates",
    location = "https://ncses.nsf.gov/surveys/earned-doctorates/2023",
    years = [],
    variables = []
), Source(
    title = "Survey of Graduate Students and Postdoctorates in Science and Engineering",
    location = "https://ncses.nsf.gov/surveys/graduate-students-postdoctorates-s-e/2023", # Same as the previous comment
    years = [ 2023 ],
    variables = [
        "Citizenship, ethnicity, and race of graduate students, by detailed field: 2023",
        "Master's and doctoral students within science, engineering, and health fields, by enrollment intensity: 2023",
        "Demographic characteristics of graduate students, postdoctoral appointees, and doctorate-holding nonfaculty researchers in science, engineering, and health: 2023",
        "Graduate students in science, engineering, and health broad fields, by degree program, citizenship, ethnicity, and race: 2023"
    ]
), Source(
    title = "National Survey of College Graduates",
    location = "https://ncses.nsf.gov/pubs/nsf23306/",
    years = [ 2021 ],
    variables = [
        "College graduates, by level of highest degree, minor field of highest degree, and labor force status: 2021",
        "Employed scientists and engineers, by sex, major field of highest degree, ethnicity, race, disability status, and type of disability: 2021",
        "Employed college graduates, by minor occupation and major field of highest degree: 2021",
        "Employed college graduates, by level of highest degree, minor occupation, and primary work activity: 2021",
        "Median annual salaries of full-time employed college graduates, by major occupation, age, level of highest degree, and sex: 2021",
        "Employment counts and median annual salaries of full-time employed scientists and engineers, by major field of highest degree, employment sector, and primary work activity: 2021",
        "College graduates, by broad field of highest degree, father's education, mother's education, level of highest degree, and median amount borrowed to finance undergraduate degree: 2021"
    ]
), Source(
    title = "Survey of Doctorate Recipients",
    location = "https://ncses.nsf.gov/surveys/doctorate-recipients/2023",
    years = [2023],
variables = [
    "Median annual salary of U.S. residing full-time employed doctoral scientists and engineers, by field of doctorate and sector of employment: 2023",
    "U.S. residing employed doctoral scientists and engineers, by field of doctorate, ethnicity, race, and sex: 2023",
    "U.S. residing doctoral scientists and engineers, by fine field of doctorate and employment status: 2023",
    "U.S. residing doctoral scientists and engineers, by field of doctorate, sex, and employment status: 2023",
    "U.S. residing doctoral scientists and engineers, by field of doctorate, ethnicity, and race: 2023",
    "Doctoral scientists and engineers, by fine field of doctorate, residence location, and sex: 2023",
    "U.S. residing employed doctoral scientists and engineers in 4-year educational institutions, by field of doctorate, sex, and faculty rank: 2023",
    "U.S. residing employed doctoral scientists and engineers in 4-year educational institutions, by broad field of doctorate, sex, tenure status, and years since doctorate: 2023",
    "U.S. residing employed doctoral scientists and engineers in 4-year educational institutions, by field of doctorate, sex, and tenure status: 2023",
    "U.S. residing doctoral scientists and engineers, by occupation and employment status: 2023",
    "U.S. residing employed doctoral scientists and engineers, by occupation, ethnicity, race, and sex: 2023",
    "U.S. residing employed minority doctoral scientists and engineers, by occupation, ethnicity, race, and sex: 2023",
    "Median annual salary of U.S. residing full-time employed doctoral scientists and engineers, by field of doctorate, ethnicity, race, and sex: 2023"]
    
),Source(
    title = "Bureau of Labor Statistics",
    location = "https://www.bls.gov/",
    years = [],
    variables = []
), Source(
    title = "Occupational Outlook Handbook",
    location = "https://www.bls.gov/ooh/",
    years = [],
    variables = []
), Source(
    title = "Occupational Employment and Wage Statistics",
    location = "https://www.bls.gov/oes/tables.htm",
    years = [],
    variables = []
), Source(
    title = "American Mathematical Society",
    location = "https://ams.org/",
    years = [],
    variables = []
    written_responses = ["Institution", "Department", "Address", "Name of person completing form", "Date", "Title", "Phone", "Email", "Fax", "Of the total full-time faculty reported in C.1, C.2, and C.3 (above), how many taught one or more courses other than mathematics or statistics in Fall 2019?", "Of the total reported in C.4, how many taught only computer sciences courses in Fall 2019?", "Institution", "Department", "Address", "Name of person completing form:", "Date", "Title", "Phone", "Email", "Fax", "Report your department's total undergraduate course enrollment (all enrollments combined) for Fall 2019.", "Report your department's total graduate course enrollment (all enrollments combined) for Fall 2019.", "Of the total full-time faculty reported in C.1, C.2, and C.3 (above), how many taught one or more courses other than mathematics or statistics in Fall 2019?", "Of the total reported in C.4, how many taught only computer sciences courses in Fall 2019?", "Institution", "Department", "Address", "Name of person completing form", "Date", "Title", "Phone", "Email", "Fax", "Report your department's total undergraduate course enrollment (all enrollments combined) for Fall 2019.", "Report your department's total graduate course enrollment (all enrollments combined) for Fall 2019.", "Of the total full-time faculty reported in C.1, C.2, and C.3 (above), how many taught one or more courses other than mathematics or statistics in Fall 2019?", "Of the total reported in C.4, how many taught only computer sciences courses in Fall 2019?", "Institution", "Department", "Chair/head", "City and State", "Name and tile of person completing this form", "Email", "Tel", "Institution", "Department", "Address", "Number of full-time faculty with 9\u201310 month appointments.", "Number of full-time faculty with 11\u201312 month appointments (for these appointments multiply the annual salaries by 0.8 before reporting them in the table).", "Name, title, and email of person completing form.", "Date", "Department address (update, if necessary)", "Department", "Institution", "Name of individual completing survey", "Email of individual completing survey", "Please report the total number of full-time positions under recruitment during academic year 2018-2019. Tenure-track positions", "Please report the total number of full-time positions under recruitment during academic year 2018-2019. Non-tenure-track positions", "For the tenure-track position(s) reported in Question 2.1: How many were open to new doctoral recipients?", "For the tenure-track position(s) reported in Question 2.1: How many were at the associate/full professor level?", "For the non-tenure-track position(s) reported in Question 2.2: How many were open to new doctoral recipients?", "For the non-tenure-track position(s) reported in Question 2.2: How many were for only one academic year?", "For the period July 1, 2018 through June 30, 2019, report the number of full-time faculty who died while in full-time service?", "For the period July 1, 2018 through June 30, 2019, report the number of full-time faculty who retired from full-time service?", "How many of those who retired were tenured (or permanent if your institution does not recognize tenure)?", "Please provide us with contact information for the individual completing this survey in case we have questions.", "Name", "Position", "Email address", "Phone Number", "Please provide your current department chair information:", "Current Chair or Head", "Chair Email", "First Name", "Last Name", "Today's Date", "Doctoral Institution", "Department/Program", "City & State", "Type of Research Doctoral Degree (e.g., PhD, Ed.D, etc.)", "Email", "When did you start this doctoral degree and when was the degree granted?", "What is the title of your dissertation?", "Who was your dissertation advisor:", "Please provide the following information (please use the full organization name and avoid acronyms)", "How many years of full-time employment in the mathematical sciences or related fields have you had prior to your current work?", "What will your basic annual salary be for this job?", "If a non-US citizen, of which country are you a citizen?", "What was your age when you received this PhD?", "Please enter any comments you wish to provide in the space below:"]
    table_inputs = ["Report your department's total undergraduate course enrollment (all enrollments combined) for Fall 2019.", "Report your department's total graduate course enrollment (all enrollments combined) for Fall 2019.", "Tenured and Tenure-eligible faculty (include tenure-track faculty who are on leave):", "Postdoctoral and Visiting faculty: Report in this subsection those (full-time) faculty who have teaching and/or research responsibilities, but for a strictly limited term of employment.", "Non-tenure-eligible faculty: Report in this subsection (full-time) faculty eligible for benefits and with an appointment that lasts at least one academic year.", "Report in this subsection faculty who are hired term-by-term, and are paid by the course.", "Report the number of bachelors degrees awarded to mathematical sciences majors within your department (include joint and double majors).", "Of those reported in D.1.a\u2013D.1.e, how many expected to enter a graduate program in mathematical sciences by fall of 2019?", "Tenured and Tenure-eligible faculty (include tenure-track faculty who are on leave)", "Postdoctoral and Visiting faculty: Report in this subsection those (full-time) faculty who have teaching and/or research responsibilities, but for a strictly limited term of employment.", "Non-tenure-eligible faculty: Report in this subsection (full-time) faculty eligible for benefits and with an appointment that lasts at least one academic year.", "Report in this subsection faculty who are hired term-by-term, and are paid by the course.", "Report the number of bachelors degrees awarded to mathematical sciences majors within your department (include joint and double majors).", "Of those reported in D.1.a\u2013D.1.e, how many expected to enter a graduate program in mathematical sciences by fall of 2019?", "Tenured and Tenure-eligible faculty (include tenure-track faculty who are on leave):", "Postdoctoral and Visiting faculty: Report in this subsection those (full-time) faculty who have teaching and/or research responsibilities, but for a strictly limited term of employment.", "Non-tenure-eligible faculty: Report in this subsection (full-time) faculty eligible for benefits and with an appointment that lasts at least one academic year.", "Part-time Appointments: Report in this section instructors who do not hold a full-time appointment for the academic year.", "Report only graduate students whose major course of study is within your department and who are actually enrolled in Fall 2019.", "Report the number of bachelors degrees awarded to mathematical sciences majors within your department (include joint and double majors).", "Of those reported in E.1.a\u2013E.1.e, how many expected to enter a graduate program in mathematical sciences by fall of 2019?", "Report the number of masters degrees awarded to mathematical sciences majors within your department (include joint and double majors).", "How many doctoral degrees were awarded between July 1, 2019 \u2013 June 30, 2020?", "PhD Recipient Name", "In each box, write the number of part-time salaried faculty whose academic-year pay falls within the given interval.", "For each pay range, enter the number of term-long sections being taught by men and by women during the fall term of AY 2019\u20132020.", "In each box, write the number of faculty, as defined below, whose academic-year salary falls within the given salary interval and professional rank. (Exclude summer salaries.)", "Among the individuals who received the tenure-track appointments: How many were NEW doctorate recipients?", "Among the individuals who received the tenure-track appointments: How many received their doctorate prior to July 1, 2018?", "Of those reported in (b) above, how many held a postdoctoral position the previous year?", "Of those just reported in (b) above, how many held a non-tenure-track position other than a postdoc?", "Among the individuals who received the non-tenure-track appointments: How many were NEW doctorate recipients?", "Among the individuals who received the non-tenure-track appointments: How many received their doctorate prior to July 1, 2018?", "Among the individuals who received the non-tenure-track appointments: How many did not hold the doctoral degree as of July 1, 2019, nor expect to receive their doctoral degree by July 1, 2020?", "Among the individuals who received the non-tenure-track appointments, how many were appointed for a single academic year with the expectation that their position would be re-advertised for recruitment during 2018-2019?", "Among the individuals who received the non-tenure-track appointments, how many were appointed to a postdoctoral position?", "For the period July 1, 2018 through June 30, 2019, report the number of full-time faculty in your department who left their position."]
    multiple_choices = ["Highest Degree Offered by Department", "Please provide the gender for your current department chair/head.", "If your institution does not recognize tenure, please check the following box and then report your full-time faculty in the appropriate lines in sections C.2 and C.3 below.", "If your department does not have undergraduate degrees in the mathematical sciences, check here .", "Highest Degree Offered by Department", "Please provide the gender for your current department chair/head.", "If your institution does not recognize tenure, please check the following box and then report your full-time faculty in the appropriate lines in sections C.2 and C.3 below.", "If your department does not have undergraduate degrees in the mathematical sciences, check here .", "Highest Degree Offered by Department", "Please provide the gender for your current department chair/head.", "If your institution does not recognize tenure, please check the following box and then report your full-time faculty in the appropriate lines in sections C.2 and C.3 below.", "If your department does not have graduate students, check here and go to Section E.", "If your department does not have undergraduate degrees in the mathematical sciences, check here .", "If your department does not award masters degrees in the mathematical sciences, check here .", "Highest degree offered by department (check one)", "Is an academic term in your institution a semester , quarter , or other?", "If your institution does not recognize tenure, please check the following box and then report those with renewable full-time appointments under non-tenure-track faculty.", "Did your department seek to fill any full-time positions requiring a doctorate during the academic year 2018-2019?", "Did your department make any appointments to the tenure-track positions under recruitment in 2018-2019?", "Did your department make any appointments to the non-tenure-track position(s) under recruitment in 2018-2019?", "Please write the name of the primary field of your dissertation research (see the list on page 4).", "Using the list on page 4, enter the two digit MR code that best describes the primary field of your dissertation.", "Check the one that describes your employment status:", "Employment status:", "Which of the following ranges best describes the maximum duration of your current employment?", "Is your job:", "If you are employed in a post-secondary academic institution, indicate which of the following best describes the category of your job:", "Which of the following categories best describes your employer?", "Are you currently actively looking for another job?", "What is your gender identity?", "What is your citizenship status?", "What is your Ethnicity?"]
    multiple_select = ["During the completion of your degree, did you do any of the following (check all that apply):", "Which of the following work activities constitute a significant portion of your primary employment?", "What is your racial background (check all that apply)?"]

), Source(
    title = "Mathematical Association of America",
    location = "https://maa.org/",
    years = [],
    variables = []
), Source(
    title = "Society for Industrial and Applied Mathematics",
    location = "https://siam.org/",
    years = [],
    variables = []
), Source(
    title = "Association for Women in Mathematics",
    location = "https://awm-math.org/",
    years = [],
    variables = []
), Source(
    title = "Conference Board of the Mathematical Sciences 2021 Survey",
    location = "www.ams.org/learning-careers/data/cbms-survey/",
    years = [2021],
    variables = ["Bachelor’s degrees in mathematics, mathematics education, statistics, and computer science in mathematics departments awarded between July 1, 2020 and June 30, 2021, by gender of degree recipient and type of department.","Bachelor’s degrees in statistics departments awarded between July 1, 2020 and June 30, 2021, by gender of degree recipient and type of department.","Enrollment (in thousands) in undergraduate mathematics, statistics, and computer science courses (including distance learning enrollments) in mathematics and statistics departments by level of course and type of department in fall 2021. Numbers in parentheses are (2010, 2015) enrollments.","Number of sections (not including distance learning) of undergraduate mathematics, statistics, and computer science courses in mathematics and statistics departments by level of course and type of department in fall 2021 with fall 2015 figures in parentheses.","Enrollments in distance/remote learning courses (meaning courses offered for credit in which half or more of the instruction occurs with the instructor and the students separated by time and/or place [e.g., courses in which half or more of the course is taught online either synchronously or asynchronously, by computer software, or by other technologies], and other sections for various freshman and sophomore courses, by type of department, in fall 2021. Includes only distance/remote courses offered in normal practice, not courses that became distance/remote due to COVID-19 pandemic. (Fall 2015 data in parentheses.)","Number of sections (excluding distance learning) of calculus-level courses in mathematics departments taught by various types of instructor, by type of department, in fall 2021 with fall 2015 figures in parentheses.","Number of sections (excluding distance learning) of introductory statistics courses taught in mathematics departments and statistics departments by type of instructor and type of department in fall 2021 with fall 2015 figures in parentheses.","Number of sections of advanced mathematics (including operations research) and statistics courses in mathematics departments and of advanced statistics courses in statistics departments taught by tenured/tenure-eligible (TTE) faculty and total number of advanced-level sections by type of department in fall 2021 with fall 2015 data in parentheses.","Number of sections (excluding distance learning) of lower-level computer science courses taught in mathematics departments by type of instructor and type of department in fall 2021 with fall 2015 figures in parentheses.","Number of sections (excluding distance learning) of middle-level computer science courses taught in mathematics departments by type of instructor and type of department in fall 2021 with fall 2015 figures in parentheses.","Average section size (excluding distance learning) for undergraduate mathematics, statistics, and computer science courses in math- ematics and statistics departments by level of course and type of department in fall 2021 with fall 2015 data, when available, in parentheses. Also, all departments’ average section sizes from previous CBMS surveys.","Average recitation size in Mainstream Calculus I and II and other Calculus I courses and in introductory statistics courses that are taught using lecture/recitation method, by type of department in fall 2021, with fall 2015 data in parentheses. Distance learning sections are not included. (A calculus course is “Mainstream” if it leads to the usual upper-division mathematical sciences courses.)","Number of faculty, and of female faculty (F), in various types of mathematics departments and PhD statistics departments by highest degree and type of department in fall 2021. (Fall 2015 figures are in parentheses, and postdocs are included in other full-time (OFT) faculty totals.)","Number of faculty, and of female faculty (F), in mathematics departments combined and of doctoral-level statistics departments in fall 2021. (Fall 2015 figures are in parentheses.)","Number of tenured, tenure-eligible, postdoctoral, and other full-time (OFT) faculty in mathematics departments at four-year colleges and universities by gender and type of department in fall 2021. (Note: Postdoctoral faculty are included in other full-time totals.)","Number of tenured, tenure-eligible, other full-time, and postdoctoral faculty in doctoral-level statistics departments by gender in fall 2021 and 2015. (Postdoctoral faculty are included in other full-time faculty totals.)","Percentage of tenured and tenure-eligible mathematics department faculty and statistics faculty at four-year colleges and universities belonging to various age groups by type of department and gender in fall 2021.","Percentages of full-time faculty belonging to various ethnic groups by gender and type of department in fall 2021. Except for round-off, the percentages within each departmental type sum to 100%.","Percentages of part-time faculty belonging to various ethnic groups by gender and type of department in fall 2021. Except for round-off, the percentages within each departmental type sum to 100%.","Percentage of sections (excluding distance learning sections) in Mainstream Calculus I and Mainstream Calculus II taught by various types of instructors in four-year mathematics departments in fall 2021, by size of sections and type of department. Also average section sizes and enrollments (not including distance learning enrollments).","Percentage of sections (excluding distance learning sections) in Non-Mainstream Calculus I and in Non-Mainstream Calculus II, III, etc. taught by various types of instructors in mathematics departments in fall 2021 by size of sections and type of department. Also average section size and enrollments (not including distance learning enrollments).","Percentage of sections (excluding distance learning sections) in Introductory Statistics courses (for non-majors) taught by various types of instructors in mathematics departments in fall 2021, by size of sections and type of department. Also average section size and enrollments (not including distance learning enrollments).","Percentage of sections (excluding distance learning sections) in Introductory Statistics courses (for non-majors) taught by various types of instructors in statistics departments in fall 2021, by size of sections and type of department. Also average section size and total (non-distance learning) enrollments.","Percentage of mathematics departments using various practices in the teaching of Introductory Statistics (no calculus prerequisite) in fall 2021 by type of department.","Instructional strategies used in Introductory Statistics courses.","Extent of success in the use of technology in Introductory Statistics.","Of departments that offered Introductory Statistics (no calculus prerequisite) in fall 2021 and where a similar course is offered outside the mathematical sciences departments, the average estimated fall 2021 enrollment of all similar courses and an estimate of the total national enrollment.","Total institutional enrollment (in thousands) and percentage of part-time enrollments in two year colleges in fall for 1980 through 2015 and projected enrollments for fall 2021. Enrollments include distance learning but not dual enrollments","Enrollments in mathematics and statistics (no computer science) courses in mathematics programs at two-year colleges in fall 1985, 1990, 1995, 2000, 2005, 2010, 2015, and 2021.","Enrollment in thousands in mathematics and statistics courses (not including dual enrollments; including distance enrollments) in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.","Enrollment in 1000s (not including dual enrollments; including distance enrollments) and percentages of total enrollment in mathematics and statistics courses by type of course in mathematics departments at two-year colleges in fall 2000, 2005, 2010, 2015, and 2021.","Percentage of two-year college mathematics departments teaching mathematics courses in fall 2015 and fall 2021.","Percentage of two-year college mathematics departments teaching selected mathematics courses in the fall terms of 2005, 2010, 2015, and 2021.","Average on-campus section size by type of course in mathematics departments at two-year colleges in fall 2010, 2015, and 2021. Also percentage of sections with enrollment above 30 in fall 2015 and 2021.","Average distance learning section size by type of course in mathematics departments at public two-year colleges in fall 2021. Also percentage of sections with enrollment above 30 in fall 2021.","Average on-campus and distance learning section size for public two-year college mathematics department courses in fall 2021.","Number of sections and number and percentage of sections taught by part-time faculty in mathematics departments at public two-year colleges by type of course in fall 2015 and 2021 (excluding distance learning and dual-enrollment sections).","Percentage of mathematics departments at public two-year colleges which implemented a Pathways course sequence in 2015 and 2021, an Intermediate Algebra prerequisite in 2021, and the types of courses implemented.","Enrollments in distance/remote learning (in 1000s) and percentage of distance/remote learning enrollments (distance learning courses are courses in which half or more of the instruction occurs with the instructor and the students separated by time and/or place facilitated by technology) among all enrollments (excluding dual enrollments) in mathematics departments at two-year colleges in fall 2010, 2015, and 2021.","Percentage of mathematics departments reporting use of distance learning in mathematics departments at two-year colleges in 2013–2021.","Percentage of departments with distance learning that described various factors as significant challenges or somewhat of a challenge in fall 2021.","Percentage of two-year colleges offering various opportunities and services to mathematics students in fall 2010, 2015, and 2021.","Number of full-time permanent faculty, full-time temporary faculty, other full-time faculty, and part-time faculty paid by two-year colleges (TYC) and by a third party (e.g., dual-enrollment instructors) in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.","Teaching assignment for full-time permanent faculty, and teaching and other duties of part-time faculty, in mathematics departments at two-year colleges in fall 2021 (2015 data in parentheses).","Number of full-time permanent faculty in 2020–2021 who were no longer part of the faculty in 2025–2016 and 2021–2022.","Percentage of full-time permanent faculty in mathematics departments at two-year colleges by highest degree in fall 2000, 2005, 2010, 2015, and 2021.","Percentage of full-time permanent faculty in mathematics programs at public two-year colleges by field and highest degree in fall 2021.","Percentage of part-time faculty in mathematics departments at two-year colleges (including those paid by a third party, as in dual-enrollment courses) by highest degree in fall 2000, 2005, 2010, 2015, and 2021.","Percentage of part-time faculty in mathematics departments at two-year colleges (including those paid by a third party, as in dual-enrollment courses) by field and highest degree in fall 2021, with 2015 data in parentheses.","Number and percentage of total full-time permanent faculty in mathematics departments at two-year colleges by gender in fall 2005, 2010, 2015, and 2021.","Percentage of full-time permanent faculty and part-time faculty in mathematics departments at public two-year colleges by gender in fall 2021. Also master’s degrees in mathematics and statistics granted in the U.S. to citizens and resident aliens, by gender, in 2019–20. Part-time faculty paid by a third party are not included.","Percentage and number of ethnic minority full-time permanent faculty in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.","Percentage of full-time permanent faculty in mathematics departments at two-year colleges by ethnicity in fall 2005, 2010, 2015, and 2021","Number and percentage of full-time permanent faculty in mathematics departments at two year colleges by ethnic group, and percentage of women within each ethnic group in fall 2021.","Percentage of full-time permanent faculty and of full-time permanent faculty under age 40 in mathematics departments at public two-year colleges by ethnic group in fall 2021. Also U.S. master’s degrees in mathematics and statistics granted in the U.S. to citizens and resident aliens by ethnic group in 2020–21.","Percentage of ethnic minority part-time faculty in mathematics departments at public two-year colleges in fall 2010, 2015, and 2021.","Number and percentage of part-time faculty in mathematics departments at public two-year colleges by ethnic group, and percentage of women within each ethnic group in fall 2021.","Percentage and number of full-time permanent faculty in mathematics departments at two-year colleges by age in fall 2005, 2010, 2015, and 2021.","Percentage of full-time permanent faculty in mathematics departments at public two-year colleges by age and by gender, and percentage of women by age in fall 2021.","Percentage of newly appointed full-time permanent faculty in mathematics departments at two-year colleges coming from various sources in fall 2015 and 2021.","Percentage of full-time permanent faculty newly appointed in mathematics departments at two-year colleges by highest degree in fall 2015 and 2021.","Percentage of full-time permanent faculty newly appointed in mathematics departments at two year colleges by ethnic group in fall 2015 and 2021. Also percentage of women within each ethnic group in fall 2021.","Percentage of two-year colleges that require periodic teaching evaluations for all full-time or all part-time faculty in fall 2015 and 2021.","Percentage of mathematics departments at public two-year colleges using various methods of evaluating teaching of full- and part-time faculty in fall 2021.","Percentage of two-year colleges that require some form of continuing education or professional development for full-time permanent faculty, and percentage of faculty using various methods to fulfill those requirements, in mathematics departments at two-year colleges in fall 2015 and 2021.","Percentage of program heads classifying various problems as “major” in mathematics departments at two-year colleges in fall 2005, 2010, 2015, and 2021.","Percentage of program heads of mathematics departments at public two-year colleges classifying various problems by severity in fall 2021."],
    written_responses = ['Name of your institution:','Name of your department:','Contact person in your department:',"Contact person's e-mail address:","Contact person's phone number including area code:",'Contact person’s mailing address:','In fall 2021, how many students are enrolled in the courses taught in a high school by your full-time or part-time faculty and through which high school students may receive both high school and college credit (through your institution)? (Include these enrollments in subsequent sections)','Enter the Fall 2021 total enrollment in all such introductory statistics courses, offered outside of the mathematical sciences, at your institution.','Enter the Fall 2021 total enrollment in all such introductory data science courses, offered outside of your department at your institution.','Report the total number of your departmental majors who received their bachelor’s degrees in the mathematical sciences or computer sciences between July 1, 2020 and June 30, 2021. Include joint majors and double majors.','Give your best estimate of the percentage of your department’s graduating majors from the previous academic year 2020-21 (reported in I1) in each of the following categories. Please make the totals add to 100 percent.','Give your best estimate of the number of all of your majors who have participated in each of the following activities over the past year September 1, 2020 – August 31, 2021.','Does your department offer interdisciplinary course(s) in any of the following areas below: (Check all that apply.) An interdisciplinary course is one in which mathematics is taught with relation to another field such as mathematics and economics, or mathematics and education; do not include calculus courses','How many students graduated with a minor in statistics from your department between July 1, 2020 and June 30, 2021?','How many semester hours of mathematics or statistics courses from your department are required by your institution’s program of certification for pre-service secondary mathematics teachers (grades 9-12)?','How many semester hours of mathematics or statistics courses from your department with a primary focus on high school mathematics from an advanced viewpoint are required in your institution’s program of certification for pre-service secondary mathematics teachers (grades 9-12)?','How many semester hours of courses in mathematics from your department are required by your institution’s program of certification for pre-service middle grades (6-8) teachers of mathematics?','How many semester hours of courses in statistics from your department are required by your institution’s program of certification for pre-service middle grades (6-8) teachers of mathematics?','How many semester hours of courses from your department on fundamental ideas of mathematics appropriate for middle grade teachers are required by your institution’s program of certification for pre-service middle grades (6-8) teachers of mathematics?','How many semester hours of courses in mathematics from your department are required by your institution’s program of certification for pre-service elementary grades (K-5) teachers of mathematics?','How many semester hours of courses in statistics from your department are required by your institution’s program of certification for pre-service elementary grades (K-5) teachers of mathematics?','How many semester hours of courses from your department on fundamental ideas of mathematics appropriate for elementary teachers are required by your institution’s program of certification for prospective elementary grades (K-5) teachers of mathematics?','Name of your campus:','To help us project enrollment for the current academic year (2021–2022), please give the following enrollment figures for the previous academic year (2020–2021) not counting summer enrollment.','Campus mailing address:','For fall 2021, what is the total number of full-time mathematics faculty in your department/program, both permanent and temporary, including those on leave, on sabbatical, or have otherwise temporarily left the department?','Of the number in B1, how many are tenured, tenure-eligible, on a tenure-track, or otherwise considered to be permanent faculty (including appointive and probationary faculty, and those who are on leave or sabbatical)? We will refer to these as “permanent full-time faculty.”','Of the number in B1 and excluding those in B2, how many are continuing fulltime faculty? We will refer to these as “non-tenure-track full-time faculty.”','Give the number of “other full-time faculty” by computing B1 minus (B2 and B3)','For the permanent full-time faculty reported in B2, give the required teaching assignment in weekly contact hours.','For the permanent full-time faculty reported in B2, give the number of office hours required weekly in association with the teaching assignment in B5a (count all office hours, including those offered online)','For the permanent full-time faculty reported in B2, how many teach extra credit hours for extra pay at your campus or within your organization?','For the permanent full-time faculty reported in B2, how many permanent faculty teach extra credit hours per week in the following categories?','For fall 2021, how many part-time mathematics faculty are teaching in your department? (Note: none of these were reported above.)','How many part-time faculty paid by your college (reported in B8a) teach 6 or more hours per week?','Give the maximum number of hours of the weekly teaching assignment that can be met by teaching distance/remote learning classes (prior to the COVID19 pandemic) as defined above.'],
    table_inputs = ['Please complete the following table giving the number of students enrolled in your dual enrollment program (as defined above) for the previous term (spring 2021) and the current fall term of 2021. (Do not include these enrollments in subsequent sections)','Which of the following courses are taught in your department in Fall 2021? You may use different titles for these courses, and may have multiple courses that match a particular course name.','Which of the following courses are taught in your department in Fall 2021, will be taught in Spring 2022, or were taught at any time in 2020-21? You may use different titles for these courses, and may have multiple courses that match a particular course name.','Please enter the total fall 2021 enrollments, number of sections, and recitation sections below, as indicated.','You reported a total of [#] sections in fall 2021, distributed by course type as shown below. For each course type, please provide the number of sections taught by tenured or tenure-eligible faculty, other full-time faculty, part-time faculty, and graduate teaching assistants.','Of the undergraduate degrees described in I1, please report the number who majored in each of the following categories. Each student should be reported only once. Include all double and joint majors1 in your totals. Use the Other Mathematics Major category for a major in your department who does not fit into one of the listed categories. (Men, women, nonbinary)'],
    multiple_choices = ['We have classified your department as being part of a university or four-year college. Do you agree?','If your college or university does not recognize tenure, check this box.','Does your department participate in any dual enrollment programs of this type?','Does your department assign any of its own full-time or part-time faculty to teach courses in a high school for which high school students may receive both high school and college credit (through your institution)?','Overall, how have attitudes towards online learning changed as a result of the COVID-19 experience?','Many colleges have conducted online instruction as a way of addressing the COVID-19 pandemic, offering online instruction either as an alternative to face-to-face instruction or as a supplement to face-to-face instruction. How is that instruction coordinated with what has normally been called distance education? Please indicate which of the following applies to your department for each listed time period, using the following definitions.','Has your department taught any distance/remote learning course (other than courses moved online in response to the COVID-19 pandemic) within the calendar years 2018-2021?','Which best characterizes the format/structure of the majority of your distance/remote learning courses (not including courses moved online in response to the COVID-19 pandemic)? (Choose one response.)','In most of your distance/remote learning courses, how are the majority of the tests administered (not including courses moved online in response to the COVID-19 pandemic? (Choose one response.)','Rate the following challenges that your department faces when creating and/or offering distance/remote learning mathematics courses. (Please check one box in each line.)','Please indicate whether the following types of faculty are actively teaching one or more courses in fall 2021.','Does your department offer any Probability and/or Statistics Courses?','Does your department offer any Computer Science courses?','Has your department offered a non-traditional “pathways” course sequence within the last five years?','Does your department offer any Precollege or Introductory Level (including Precalculus) mathematics courses for credit (courses E1-E12) in Fall 2021?','How often are each of the following instructional strategies used in the Precollege and Introductory Level mathematics courses (courses E1-E12) you offered for credit in Fall 2021?','Does your department offer an Introductory Statistics (no calculus prerequisite) course (course F1) in Fall 2021?','How many different kinds of introductory statistics courses designed for non-majors that have no calculus prerequisite does your department offer? (e.g. statistics for social scientists, for life scientists, or as general education courses for a broad audience)','How often are each of these instructional strategies used in the Introductory Statistics courses taught in your department in Fall 2021?','How successful is your program in adopting each of the following use of technology in your Introductory Statistics (no calculus prerequisite) courses taught in Fall 2021?','Are there other introductory statistics courses at your institution, offered by departments outside of the mathematical sciences?','Are there introductory data science courses at your institution offered by other departments?','To what extent must majors in your department complete the following? Check one box in each row.','Many departments today use a spectrum of program-assessment methods. Please indicate whether each of the following apply to your department’s undergraduate program-assessment efforts during the last six years.','Please indicate the extent to which the following activities have taken place in the past year in your department in response to increased national attention to equity, diversity, and inclusion issues (here the term “demographic” includes race, ethnicity, gender, disability status, and other characteristics of individuals)','For each of the following opportunities, indicate whether or not it is available to your undergraduate mathematical sciences students through your department or institutions.','Does your department offer a minor in statistics?','Does your department offer a major in statistics?','To what extent must statistics majors in your department complete the following? Check one box in each row.','Does your institution allow a student to meet an institutional or divisional graduation requirement in the mathematical sciences using an Advanced Placement course (taken while the student was in high school)?','Does your institution offer a program of study that leads to obtaining credentials to teach mathematics in public high schools (any license that includes grades 9-12) in your state?','Considering the teacher preparation program at your institution, in each of the following core areas indicate whether the core area is required of all students seeking mathematics certification, if the course is generally taken by those seeking certification (if it is not required), and if in that core area your department offers a special course that is specifically designed for pre-service secondary mathematics teachers.','Does your institution offer a program of study that leads to obtaining credentials to teach mathematics in public middle schools (any license that includes grades 6-8) in your state?','Does your institution offer a program of study that leads to obtaining credentials to teach mathematics in public elementary schools (any license that includes grades K-5) in your state?','We have classified your department as belonging to a two-year college or to a college campus within a two-year college system, or to a two-year branch of a university system. Do you agree?','What is the unit (= academic discipline group) that most directly administers the mathematics program on your campus?','Does your college organize its developmental education, including mathematics, in a separately administered department or division?','Are office hours required by college policy for the part-time faculty paid by your college (reported in B8a)?','Overall, how have attitudes towards online learning changed as a result of the COVID-19 experience?','Many colleges have conducted online instruction as a way of addressing the COVID-19 pandemic, offering online instruction either as an alternative to face-to-face instruction or as a supplement to face-to-face instruction. How is that instruction coordinated with what has normally been called distance education? Please indicate which of the following applies to your department for each listed time period, using the following definitions.','Has your department taught any distance/remote learning courses (other than courses moved online in response to the COVID-19 pandemic) in 2018-2021? ','Which best characterizes the delivery format of the majority of your distance/remote learning courses (not including courses moved online in response to the COVID-19 pandemic)? (Check one box.)','In most of your distance/remote learning courses, how and where do students take the majority of their tests (not including courses moved online in response to the COVID-19 pandemic)? (Check one box.)','Rate the following challenges that your department faces when creating and/or offering distance/remote learning mathematics courses. (Please check one box in each line.)','Has your mathematics department or developmental education department offered a “pathways” course sequence within the last five years?','Which of the following pathways courses or course sequences have you offered within the last five years?','How often are each of the following instructional strategies used in courses below the level of Calculus (courses F1-F10 in Section F) you offered for credit in Fall 2021?']

), Source(
    title = "IPUMS",
    location = "https://ipums.org/",
    years = [ 2013 ],
    variables = [
        "Undergraduate loans: total funds borrowed"
        "Year of first bachelor's degree pre-2003 (5-year intervals)",
        "Year of first bachelor degree 2003-onward (5-year intervals)",
        "Field of major for first bachelor degree code",
        "Field of major for first bachelor degree (major group)",
        "Location of school awarding first bachelor's degree (region)",
        "Location of school awarding first bachelor degree (US/non-US)",
        "Education code for first intended major (best code)",
        "Field of intended bachelors degree (major group)",
        "Field of intended bachelors degree (minor group)",
        "First intended major: undecided",
        "Undergraduate grade-point average (GPA)",
        "Financial support for first bachelor degree: Assistantship/work study",
        "Financial support for first bachelor degree: Employer",
        "Financial support for first bachelor degree: Earnings from employment",
        "Financial support for first bachelor degree: Gifts",
        "Financial support for first bachelor degree: Grants",
        "Financial support for first bachelor degree: Loans",
        "Financial support for first bachelor degree: Other",
        "Financial support for first bachelor degree: Loans from relatives",
        "Undergraduate loans: remaining balance",
        "Children indicator: aged 12-17",
        "Children indicator: aged 12-18",
        "Number of children: aged 18 or older",
        "Children indicator: aged 18 or older",
        "Children indicator: age 19 or older",
        "Age",
        "Birth year",
        "Gender",
        "Minority indicator",
        "Race/ethnicity",
        "Place of birth",
        "US citizenship status",
        "Type of US citizen",
        "Type of visa held when first came to US",
        "Total number of children",
        "Number of children: under age 2",
        "Children indicator: under age 2",
        "Number of children: under age 6",
        "Children indicator: under age 6",
        "Number of children: aged 2-5",
        "Children indicator: ages 2-5",
        "Number of children: aged 6-11",
        "Children indicator: ages 6-11",
        "Children indicator: under 12",
        "Number of children: aged 12-17",
        "Career preparation: teaching skills",
        "Career preparation: collaboration/team work skills",
        "Career preparation: writing skills",
        "Year of highest degree since doctorate ",
        "Field of major for highest degree since doctorate ",
        "Field of major for highest degree since doctorate (major group)",
        "Highest degree since doctorate: course costs paid for by employer",
        "Satisfaction with doctoral program",
        "First doctoral degree received between June 1990 and June 1996",
        "Completing doctoral degree affected: level of responsibility",
        "Completing doctoral degree affected: management activities",
        "Completing doctoral degree affected: other",
        "Completing doctoral degree affected: interesting/rewarding work",
        "Completing doctoral degree affected: job security",
        "Completing doctoral degree affected: technically demanding work",
        "Completing doctoral degree affected: salary level",
        "No more training desired",
        "More training: first area",
        "More training: second area",
        "Career preparation: oral communication skills",
        "Career preparation: computer skills",
        "Career preparation: establishing contacts",
        "Career preparation: research integrity/ethics",
        "Career preparation: problem solving skills",
        "Career preparation: subject matter knowledge",
        "Career preparation: management/administrative skills",
        "Career preparation: quantitative skills",
        "Graduate loans: remaining balance",
        "Graduate loans: total funds borrowed",
        "Type of highest certificate or degree",
        "Year of highest degree pre-2003 (5 year intervals)",
        "Year of highest degree 2003-onward (5 year intervals)",
        "Field of major for highest degree ",
        "Field of major for highest degree (major group)",
        "Location of school awarding highest degree",
        "School awarding highest degree located in the US",
        "Financial support for highest degree: assistantship/work study",
        "Financial support for highest degree: financial assistance from employer",
        "Financial support for highest degree: earnings from employment",
        "Financial support for highest degree: gifts",
        "Financial support for highest degree: grants",
        "Financial support for highest degree: loans",
        "Financial support for highest degree: other",
        "Financial support for highest degree: loans from parents",
        "Likelihood of choosing same field of study for highest degree",
        "Type of degree",
        "Year of most recent degree (5-year intervals",
        "Year of most recent degree (5-year intervals",
        "Field of major for most recent degree",
        "Field of study of major for most recent degree (major group)",
        "Location of school awarding most recent degree",
        "School awarding most recent degree located in the US",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Financial support",
        "Job market for other than postdocs",
        "Job market for postdocs",
        "Individual identification number[preselected]",
        "Reference ID number (original)",
        "Survey year[preselected]",
        "SESTAT weight[preselected]",
        "Sample identifier[preselected]",
        "Survey identifier[preselected]",
        "Survey cohort",
        "Survey mode",
        "Sequence number",
        "Two-year associates degree ",
        "Not held career path job since receiving doctorate ",
        "Most important resource for career search ",
        "Second most important resource for career search ",
        "Job seeking resources used: initiated direct contacts ",
        "Job seeking resources used: electronic postings ",
        "Job seeking resources used: faculty/advisors ",
        "Job seeking resources used: colleagues/friends ",
        "Job seeking resources used: newspapers ",
        "Job seeking resources used: other ",
        "Job seeking resources used: professional journals ",
        "Job seeking resources used: professional meetings ",
        "Job seeking resources used: college placement office ",
        "Job seeking resources used: professional recruiters ",
        "Search for job limited by: debt ",
        "Search for job limited by: family responsibilities ",
        "Search for job limited by: desire to not relocate ",
        "Search for job limited by: suitable job not available ",
        "Search for job limited by: other ",
        "Search for job limited by: spouse's career ",
        "Reasons for not working: family responsibilities ",
        "Reasons for not working: illness/disability ",
        "Reasons for not working: layoff ",
        "Reasons for not working: did not need/want to work ",
        "Reasons for not working: suitable job not available ",
        "Reasons for not working: other ",
        "Reasons for not working: illness, retired or other (combined) ",
        "Reasons for not working: retired ",
        "Reasons for not working: student ",
        "Career-path job ",
        "Seeking career-path job ",
        "Time started career-path job ",
        "Sought career path job ",
        "Sought or held career path job ",
        "Held or accepted career path job ",
        "When began working on job ",
        "How doctoral degree would help career ",
        "Still holding career path job ",
        "Relationship of career path job to doctoral degree field ",
        "Work wanted after completing doctorate: management/administration ",
        "Work wanted after completing doctorate: professional practice ",
        "Work wanted after completing doctorate: research ",
        "Work wanted after completing doctorate: teaching ",
        "Work wanted after completing doctorate: other ",
        "Desired employment setting at beginning of doctorate ",
        "New job offered what level of: responsibility ",
        "New job offered what level of: salary ",
        "New job offered what level of: knowledge/skill utilization ",
        "Time elapsed between receiving doctorate and accepting career path job ",
        "Attended community college ",
        "Reasons attend community college: high school advanced placement program ",
        "Reasons attend community college: complete associates degree ",
        "Reasons attend community college: complete credit towards bachelors degree ",
        "Reasons attend community college: change academic/occupational field ",
        "Reasons attend community college: prepare for college ",
        "Reasons attend community college: financial reasons ",
        "Reasons attend community college: complete high school equivalency ",
        "Reasons attend community college: leisure ",
        "Reasons attend community college: other ",
        "Reasons attend community college: increase opportunities for promotion ",
        "Reasons attend community college: acquire further skills in field ",
        "Reasons for not taking courses: needed break ",
        "Reasons for not taking courses: no longer certain of field ",
        "Reasons for not taking courses: family ",
        "Reasons for not taking courses: financial reasons ",
        "Reasons for not taking courses: achieved educational goals ",
        "Reasons for not taking courses: job ",
        "Reasons for not taking courses: moved ",
        "Reasons for not taking courses: waiting for next school term ",
        "Reasons for not taking courses: other ",
        "Reasons for not taking courses: most important reason ",
        "Reasons for not taking courses: second most important reason ",
        "School-related costs paid by employer ",
        "Sources of financial support for courses since college: assistantships/work study ",
        "Sources of financial support for courses since college: employer ",
        "Sources of financial support for courses since college: earnings from employment ",
        "Sources of financial support for courses since college: gifts parents/relatives ",
        "Sources of financial support for courses since college: grants/scholarships/etc. ",
        "Sources of financial support for courses since college: loans from institution ",
        "Sources of financial support for courses since college: other ",
        "Sources of financial support for courses since college: loans from parents/relatives ",
        "Likelihood of taking additional college courses ",
        "Full-time/part-time student status ",
        "Taking courses during reference week ",
        "Type of degree working on during reference week ",
        "Took college courses after completing most recent degree ",
        "Type of degree working on since after college ",
        "Type of degree working on since most recent degree ",
        "Completed a degree since the last survey ",
        "Enrolled in other than courses after completing most recent degree ",
        "Took courses or enrolled in other way after completing most recent degree ",
        "Region, college/university attended during reference week (US/non-US) ",
        "Field of major for field of study after most recent degree ",
        "Field of study after earning degree ",
        "Field of major for current degree (detailed code) ",
        "Field of major for current degree (minor code) ",
        "Field of major for current degree (major code) ",
        "Field of major for degree working on during the week of February 1st ",
        "No primary field of study in courses after college ",
        "Reasons for taking courses: increase advancement opportunities ",
        "Reasons for taking courses: further education before career ",
        "Reasons for taking courses: facilitate academic/occupational field change ",
        "Reason for taking courses during reference week: expected/required by employer ",
        "Reason for taking courses during reference week: prepare for graduate school ",
        "Reason for taking courses during reference week: leisure/personal interest ",
        "Reason for taking courses during reference week: licensure/certification ",
        "Reason for taking courses during reference week: other ",
        "Reason for taking courses during reference week: grad school, required by employer, other ",
        "Reason for taking courses during reference week: gain further skills in field ",
        "Reasons for taking courses: expected/required by employer ",
        "Reasons for taking courses: prepare for graduate school ",
        "Employer sector ",
        "Employer sector (detailed code) ",
        "Size of employer ",
        "Employer: main business ",
        "Principal employer came into being as a new business within last 5 years ",
        "Employer located in the US ",
        "US region code for employer ",
        "Federal government support indicator ",
        "Federal agency supporting work: Agriculture ",
        "Federal agency supporting work: AID ",
        "Federal agency supporting work: Commerce ",
        "Federal agency supporting work: Education ",
        "Federal agency supporting work: Agency unknown ",
        "Federal agency supporting work: Defense ",
        "Federal agency supporting work: Energy ",
        "Federal agency supporting work: Transportation ",
        "Federal agency supporting work: EPA ",
        "Federal agency supporting work: HHS ",
        "Federal agency supporting work: HUD ",
        "Federal agency supporting work: Interior ",
        "Federal agency supporting work: Justice ",
        "Federal agency supporting work: Labor ",
        "Federal agency supporting work: NASA ",
        "Federal agency supporting work: NIH ",
        "Federal agency supporting work: NRC ",
        "Federal agency supporting work: NSF ",
        "Federal agency supporting work: Other ",
        "Federal agency supporting work: State ",
        "Federal agency supporting work: VA ",
        "Reason job unrelated to doctoral degree: career change ",
        "Reason job unrelated to doctoral degree: working conditions ",
        "Reason job unrelated to doctoral degree: family-related reasons ",
        "Reason job unrelated to doctoral degree: job location ",
        "Reason job unrelated to doctoral degree: job in doctoral field not available ",
        "Reason job unrelated to doctoral degree: other ",
        "Reason job unrelated to doctoral degree: pay/promotion opportunities ",
        "Concerned about someone else in household losing job ",
        "No other working adult in household ",
        "Reasons for losing/leaving job: other ",
        "Reasons for losing/leaving job: work reorganized/restructured ",
        "Reasons for losing/leaving job: company had insufficient revenue ",
        "Reasons for losing/leaving job: self-operated business ended ",
        "Reasons for losing/leaving job: company taken over ",
        "Lost or left job due to employer closing or downsizing ",
        "Year last worked ",
        "Previously retired ",
        "Reasons for working part-time: retired ",
        "Working part-time but wanted to work full-time ",
        "Reasons for working part-time: family ",
        "Reasons for working part-time: illness/disability ",
        "Reasons for working part-time: not need/want work ",
        "Reasons for working part-time: suitable full-time job not available ",
        "Reasons for working part-time: other ",
        "Reasons for working part-time: student ",
        "Labor force status ",
        "Working for pay during reference week ",
        "Full-time/part-time status ",
        "Working both current and previous reference weeks ",
        "Employment status, current and previous reference weeks ",
        "Full-time, years of professional work experience ",
        "Part-time, years of professional work experience ",
        "Principal job hours worked ",
        "Principal job: hours per week typically worked (group) ",
        "Principal job salary: weeks per year basis ",
        "Principal job weeks salary based on year (group) ",
        "Available benefits: health insurance ",
        "Available benefits: pension/retirement plan ",
        "Available benefits: profit-sharing plan ",
        "Available benefits: paid vacation/sick/personal days ",
        "Not working, looking for work ",
        "Have not found new job ",
        "Months to find new job ",
        "Preferred type of working arrangement ",
        "Concerned about losing job ",
        "Year, left/lost job ",
        "Reasons for losing/leaving job: company closed down ",
        "Reasons for losing/leaving job: company moved ",
        "Year received high school diploma (group) ",
        "Place attended high school (recode) ",
        "No high school diploma (did not finish high school) ",
        "Salary (annualized) ",
        "Total earned income before deductions in previous year (public use) ",
        "Total household income: 1996 ",
        "CPI conversion factor - current year ",
        "CPI conversion factor - previous year ",
        "International collaboration activity: travel abroad for collaboration ",
        "International collaboration activity: foreign collaborators travel to US ",
        "International collaboration activity: use web-based/virtual technology ",
        "Work benefits from: long distance communication ",
        "Work benefits from: long-term visits ",
        "Work benefits from: short-term visits ",
        "Conducted research outside US ",
        "Length of last trip conducting research outside US ",
        "Would consider conducting research outside US ",
        "Increasing interest in research outside US: family-related reasons ",
        "Increasing interest in research outside US: better financial support ",
        "Increasing interest in research outside US: better foreign language training ",
        "Increasing interest in research outside US: better access to research opportunities ",
        "Increasing interest in research outside US: other ",
        "Increasing interest in research outside US: better sabbatical leave policy ",
        "Reason not conducted research outside US: family-related reasons ",
        "Reason not conducted research outside US: no funding ",
        "Reason not conducted research outside US: no host ",
        "Reason not conducted research outside US: no interest ",
        "Reason not conducted research outside US: concerned about losing place ",
        "Reason not conducted research outside US: lack of foreign language skills ",
        "Reason not conducted research outside US: not relevant to my career ",
        "Reason not conducted research outside US: other ",
        "Reason not conducted research outside US: no time ",
        "International collaboration indicator ",
        "International collaboration activity: communicate by phone/email ",
        "Relationship with principal employer: short term ",
        "Relationship with principal employer: self-employed ",
        "Relationship with principal employer: job sharing ",
        "Relationship with principal employer: temp/employment agency ",
        "Area or tech used during typical week: advanced materials ",
        "Area or tech used during typical week: biotech ",
        "Area or tech used during typical week: high performance computing ",
        "Area or tech used during typical week: semiconductor devices ",
        "Area or tech used during typical week: flexible manufacturing, robotics ",
        "Area or tech used during typical week: software producibility ",
        "Area or tech used during typical week: sensor and signal processing ",
        "Energy-related activity most involved in work ",
        "Energy source involved most ",
        "Most important reason for working outside field of highest degree ",
        "Second most important reason for working outside field of highest degree ",
        "Reason for working outside field of highest degree: career change ",
        "Reason for working outside field of highest degree: working conditions ",
        "Reason for working outside field of highest degree: family-related reasons ",
        "Reason for working outside field of highest degree: job location ",
        "Reason for working outside field of highest degree: suitable job not available ",
        "Reason for working outside field of highest degree: Other ",
        "Reason for working outside field of highest degree: pay/promotion ",
        "Faculty rank and tenure status ",
        "Academic position: adjunct faculty ",
        "Academic position: dean or president ",
        "Academic position: not applicable ",
        "Academic position: research assistant, teaching assistant or other ",
        "Academic position: postdoc ",
        "Academic position: research faculty ",
        "Academic position: teaching faculty ",
        "Alternative work arrangement ",
        "Main reason for alternative work arrangement ",
        "Second most important reason for alternative work arrangement ",
        "Reason for alternative work arrangement: own boss ",
        "Reason for alternative work arrangement: gain experience ",
        "Reason for alternative work arrangement: family-related reasons ",
        "Reason for alternative work arrangement: schedule flexibility ",
        "Reason for alternative work arrangement: other ",
        "Reason for alternative work arrangement: better pay ",
        "Reason for alternative work arrangement: status changed to temporary ",
        "Reason for alternative work arrangement: school or training program ",
        "Reason for alternative work arrangement: only type of work I could find ",
        "Relationship with principal employer: work from home ",
        "Relationship with principal employer: work contracted out by employer ",
        "Relationship with principal employer: other ",
        "Job satisfaction ",
        "Satisfaction principal job's opportunities for advancement ",
        "Satisfaction principal job benefits ",
        "Satisfaction principal job's intellectual challenge ",
        "Satisfaction principal job's degree of independence ",
        "Satisfaction principal job's job location ",
        "Satisfaction principal job's level of responsibility ",
        "Satisfaction principal job salary ",
        "Satisfaction principal job's job security ",
        "Satisfaction principal job's contribution to society ",
        "Principal job related to highest degree ",
        "Job code for principal job ",
        "Job code for principal job (major group) ",
        "Job code for principal job (detailed code) ",
        "Relationship of second job to highest degree ",
        "Second job during reference week ",
        "Job code for second job ",
        "Job code for second job (major group) ",
        "Respondent location ",
        "Reasons for coming to U.S.: most important reason ",
        "Reasons for coming to U.S.: second most important reason ",
        "Factors important to come to U.S.: educational opportunities ",
        "Factors important to come to U.S.: family-related reasons ",
        "Factors important to come to U.S.: scientific/professional infrastructure ",
        "Factors important to come to U.S.: job/economic opportunities ",
        "Factors important to come to U.S.: other ",
        "Respondent location ",
        "Reasons for coming to U.S.: most important reason ",
        "Reasons for coming to U.S.: second most important reason ",
        "Factors important to come to U.S.: educational opportunities ",
        "Factors important to come to U.S.: family-related reasons ",
        "Factors important to come to U.S.: scientific/professional infrastructure ",
        "Factors important to come to U.S.: job/economic opportunities ",
        "Factors important to come to U.S.: other ",
        "Work activities on principal job: professional services ",
        "Work activities on principal job: teaching ",
        "Work activities on principal job: accounting, finance, contracts ",
        "Work activities on principal job : applied research ",
        "Work activities on principal job: basic research ",
        "Work activities on principal job: computer applications ",
        "Work on principal job: work with others in same organization ",
        "Work on principal job: work with immediate group or team ",
        "Work on principal job: work with others in other US organization ",
        "Supervisory work ",
        "Number of papers (co)authored presented ",
        "Number of papers presented (intervaled) ",
        "Named as inventor for U.S patent ",
        "Number of articles authored (intervals) ",
        "Number of articles authored ",
        "Number of professional society memberships ",
        "Attended professional meetings in past year ",
        "Books or monographs (co)authored accepted for publication indicator ",
        "Work similar to what you expected to be doing ",
        "Most hours, work activity ",
        "Summarized primary work activity ",
        "Second most hours, work activity ",
        "Summarized secondary work activity ",
        "Area devoted most hours ",
        "Activity, computer applications ",
        "Activity, development and design ",
        "Activity, management/sales ",
        "Activity, research and development ",
        "Activity, research, development, and teaching ",
        "Activity, research (basic and/or applied) ",
        "Activity, teaching ",
        "Work activities on principal job: development ",
        "Work activities on principal job: design ",
        "Work activities on principal job: employee relations ",
        "Work activities on principal job: management and administration ",
        "Work activities on principal job: other ",
        "Work activities on principal job: production, operations, maintenance ",
        "Work activities on principal job: quality or productivity management ",
        "Work activities on principal job: sales, purchasing, marketing ",
        "Job code for last job (major group) ",
        "Job code for last job (public use) ",
        "Reason for changing employer or job: change in career/professional interests ",
        "Reason for changing employer or job: working conditions ",
        "Reason for changing employer or job: family-related reasons ",
        "Reason for changing employer or job: laid off/job terminated ",
        "Reason for changing employer or job: job location ",
        "Reason for changing employer or job: other ",
        "Reason for changing employer or job: pay, promotion ",
        "Reason for changing employer or job: retired ",
        "Reason for changing employer or job: school-related reasons ",
        "Offered buy-out ",
        "Job code for principal job in 1988 (major group) ",
        "Job code for principal job in 1988 ",
        "Technical expertise required by spouse/partner job: sciences ",
        "Technical expertise required by spouse/partner job: other ",
        "Technical expertise required by spouse/partner Job: social sciences ",
        "Attended work-related training ",
        "Most important reason for taking work-related training ",
        "Reason for attending training: increase advancement opportunities ",
        "Reason for attending training: facilitate occupation change ",
        "Reason for attending training: facilitate occupation change to different field ",
        "Reason for attending training: required/expected by employer ",
        "Reason for attending training: licensure/certification ",
        "Reason for attending training: learn skills for recently acquired position ",
        "Reason for attending training: increase advancement opportunities in current occupation ",
        "Reason for attending training: other ",
        "Reason for attending training: leisure/personal interest ",
        "Reason for attending training: acquire further skills/knowledge ",
        "Area of work-related training: general professional training ",
        "Area of work-related training: management training ",
        "Area of work-related training: other ",
        "Area of work-related training: technical training ",
        "Licensed/certified in occupation ",
        "Job required technical expertise: natural sciences ",
        "Job required technical expertise: other ",
        "Job required technical expertise: social sciences ",
    ]
), Source(
    title = "Data.gov",
    location = "https://data.gov/",
    years = [],
    variables = []
), Source(
    title = "Harvard Dataverse",
    location = "https://dataverse.harvard.edu/",
    years = [],
    variables = []
), Source(
    title = "Pewresearch",
    location = "https://pewresearch.org/",
    years = [],
    variables = []
), Source(
    title = "Urban Institute",
    location = "https://urban.org/",
    years = [],
    variables = []
)]

ts = []
ls = []
ys = []
vs = []
mcs = []
mss = []
tis = []
wrs = []

for source in sources:
    ts.append(source.title)
    ls.append(source.location)
    ys.append(source.years)
    vs.append(source.variables)
    mcs.append(source.multiple_choices)
    mss.append(source.multiple_selects)
    tis.append(source.table_inputs)
    wrs.append(source.written_responses)


df = pd.DataFrame({
    "title": ts,
    "location": ls,
    "years": ys,
    "variables": vs,
    "multiple choices": mcs,
    "multiple selects": mss,
    "table inputs": tis,
    "written responses": wrs
})

df.to_csv("data/variables.csv")
df.to_hdf("data/collected_data.h5", key = "variables")
